//
//  Category.swift
//  Yelp
//
//  Created by Josh Jeong on 4/7/17.
//  Copyright © 2017 Timothy Lee. All rights reserved.
//

import Foundation

class Category {
    
    func getFoodCategories() -> [[String:String]] {
        return [["title" : "Afghan", "filter_type": "category_filter", "value": "afghani"],
                ["title" : "African", "filter_type": "category_filter", "value": "african"],
                ["title" : "American, New", "filter_type": "category_filter", "value": "newamerican"],
                ["title" : "American, Traditional", "filter_type": "category_filter", "value": "tradamerican"],
                ["title" : "Arabian", "filter_type": "category_filter", "value": "arabian"],
                ["title" : "Argentine", "filter_type": "category_filter", "value": "argentine"],
                ["title" : "Armenian", "filter_type": "category_filter", "value": "armenian"],
                ["title" : "Asian Fusion", "filter_type": "category_filter", "value": "asianfusion"],
                ["title" : "Asturian", "filter_type": "category_filter", "value": "asturian"],
                ["title" : "Australian", "filter_type": "category_filter", "value": "australian"],
                ["title" : "Austrian", "filter_type": "category_filter", "value": "austrian"],
                ["title" : "Baguettes", "filter_type": "category_filter", "value": "baguettes"],
                ["title" : "Bangladeshi", "filter_type": "category_filter", "value": "bangladeshi"],
                ["title" : "Barbeque", "filter_type": "category_filter", "value": "bbq"],
                ["title" : "Basque", "filter_type": "category_filter", "value": "basque"],
                ["title" : "Bavarian", "filter_type": "category_filter", "value": "bavarian"],
                ["title" : "Beer Garden", "filter_type": "category_filter", "value": "beergarden"],
                ["title" : "Beer Hall", "filter_type": "category_filter", "value": "beerhall"],
                ["title" : "Beisl", "filter_type": "category_filter", "value": "beisl"],
                ["title" : "Belgian", "filter_type": "category_filter", "value": "belgian"],
                ["title" : "Bistros", "filter_type": "category_filter", "value": "bistros"],
                ["title" : "Black Sea", "filter_type": "category_filter", "value": "blacksea"],
                ["title" : "Brasseries", "filter_type": "category_filter", "value": "brasseries"],
                ["title" : "Brazilian", "filter_type": "category_filter", "value": "brazilian"],
                ["title" : "Breakfast & Brunch", "filter_type": "category_filter", "value": "breakfast_brunch"],
                ["title" : "British", "filter_type": "category_filter", "value": "british"],
                ["title" : "Buffets", "filter_type": "category_filter", "value": "buffets"],
                ["title" : "Bulgarian", "filter_type": "category_filter", "value": "bulgarian"],
                ["title" : "Burgers", "filter_type": "category_filter", "value": "burgers"],
                ["title" : "Burmese", "filter_type": "category_filter", "value": "burmese"],
                ["title" : "Cafes", "filter_type": "category_filter", "value": "cafes"],
                ["title" : "Cafeteria", "filter_type": "category_filter", "value": "cafeteria"],
                ["title" : "Cajun/Creole", "filter_type": "category_filter", "value": "cajun"],
                ["title" : "Cambodian", "filter_type": "category_filter", "value": "cambodian"],
                ["title" : "Canadian", "filter_type": "category_filter", "value": "New)"],
                ["title" : "Canteen", "filter_type": "category_filter", "value": "canteen"],
                ["title" : "Caribbean", "filter_type": "category_filter", "value": "caribbean"],
                ["title" : "Catalan", "filter_type": "category_filter", "value": "catalan"],
                ["title" : "Chech", "filter_type": "category_filter", "value": "chech"],
                ["title" : "Cheesesteaks", "filter_type": "category_filter", "value": "cheesesteaks"],
                ["title" : "Chicken Shop", "filter_type": "category_filter", "value": "chickenshop"],
                ["title" : "Chicken Wings", "filter_type": "category_filter", "value": "chicken_wings"],
                ["title" : "Chilean", "filter_type": "category_filter", "value": "chilean"],
                ["title" : "Chinese", "filter_type": "category_filter", "value": "chinese"],
                ["title" : "Comfort Food", "filter_type": "category_filter", "value": "comfortfood"],
                ["title" : "Corsican", "filter_type": "category_filter", "value": "corsican"],
                ["title" : "Creperies", "filter_type": "category_filter", "value": "creperies"],
                ["title" : "Cuban", "filter_type": "category_filter", "value": "cuban"],
                ["title" : "Curry Sausage", "filter_type": "category_filter", "value": "currysausage"],
                ["title" : "Cypriot", "filter_type": "category_filter", "value": "cypriot"],
                ["title" : "Czech", "filter_type": "category_filter", "value": "czech"],
                ["title" : "Czech/Slovakian", "filter_type": "category_filter", "value": "czechslovakian"],
                ["title" : "Danish", "filter_type": "category_filter", "value": "danish"],
                ["title" : "Delis", "filter_type": "category_filter", "value": "delis"],
                ["title" : "Diners", "filter_type": "category_filter", "value": "diners"],
                ["title" : "Dumplings", "filter_type": "category_filter", "value": "dumplings"],
                ["title" : "Eastern European", "filter_type": "category_filter", "value": "eastern_european"],
                ["title" : "Ethiopian", "filter_type": "category_filter", "value": "ethiopian"],
                ["title" : "Fast Food", "filter_type": "category_filter", "value": "hotdogs"],
                ["title" : "Filipino", "filter_type": "category_filter", "value": "filipino"],
                ["title" : "Fish & Chips", "filter_type": "category_filter", "value": "fishnchips"],
                ["title" : "Fondue", "filter_type": "category_filter", "value": "fondue"],
                ["title" : "Food Court", "filter_type": "category_filter", "value": "food_court"],
                ["title" : "Food Stands", "filter_type": "category_filter", "value": "foodstands"],
                ["title" : "French", "filter_type": "category_filter", "value": "french"],
                ["title" : "French Southwest", "filter_type": "category_filter", "value": "sud_ouest"],
                ["title" : "Galician", "filter_type": "category_filter", "value": "galician"],
                ["title" : "Gastropubs", "filter_type": "category_filter", "value": "gastropubs"],
                ["title" : "Georgian", "filter_type": "category_filter", "value": "georgian"],
                ["title" : "German", "filter_type": "category_filter", "value": "german"],
                ["title" : "Giblets", "filter_type": "category_filter", "value": "giblets"],
                ["title" : "Gluten-Free", "filter_type": "category_filter", "value": "gluten_free"],
                ["title" : "Greek", "filter_type": "category_filter", "value": "greek"],
                ["title" : "Halal", "filter_type": "category_filter", "value": "halal"],
                ["title" : "Hawaiian", "filter_type": "category_filter", "value": "hawaiian"],
                ["title" : "Heuriger", "filter_type": "category_filter", "value": "heuriger"],
                ["title" : "Himalayan/Nepalese", "filter_type": "category_filter", "value": "himalayan"],
                ["title" : "Hong Kong Style Cafe", "filter_type": "category_filter", "value": "hkcafe"],
                ["title" : "Hot Dogs", "filter_type": "category_filter", "value": "hotdog"],
                ["title" : "Hot Pot", "filter_type": "category_filter", "value": "hotpot"],
                ["title" : "Hungarian", "filter_type": "category_filter", "value": "hungarian"],
                ["title" : "Iberian", "filter_type": "category_filter", "value": "iberian"],
                ["title" : "Indian", "filter_type": "category_filter", "value": "indpak"],
                ["title" : "Indonesian", "filter_type": "category_filter", "value": "indonesian"],
                ["title" : "International", "filter_type": "category_filter", "value": "international"],
                ["title" : "Irish", "filter_type": "category_filter", "value": "irish"],
                ["title" : "Island Pub", "filter_type": "category_filter", "value": "island_pub"],
                ["title" : "Israeli", "filter_type": "category_filter", "value": "israeli"],
                ["title" : "Italian", "filter_type": "category_filter", "value": "italian"],
                ["title" : "Japanese", "filter_type": "category_filter", "value": "japanese"],
                ["title" : "Jewish", "filter_type": "category_filter", "value": "jewish"],
                ["title" : "Kebab", "filter_type": "category_filter", "value": "kebab"],
                ["title" : "Korean", "filter_type": "category_filter", "value": "korean"],
                ["title" : "Kosher", "filter_type": "category_filter", "value": "kosher"],
                ["title" : "Kurdish", "filter_type": "category_filter", "value": "kurdish"],
                ["title" : "Laos", "filter_type": "category_filter", "value": "laos"],
                ["title" : "Laotian", "filter_type": "category_filter", "value": "laotian"],
                ["title" : "Latin American", "filter_type": "category_filter", "value": "latin"],
                ["title" : "Live/Raw Food", "filter_type": "category_filter", "value": "raw_food"],
                ["title" : "Lyonnais", "filter_type": "category_filter", "value": "lyonnais"],
                ["title" : "Malaysian", "filter_type": "category_filter", "value": "malaysian"],
                ["title" : "Meatballs", "filter_type": "category_filter", "value": "meatballs"],
                ["title" : "Mediterranean", "filter_type": "category_filter", "value": "mediterranean"],
                ["title" : "Mexican", "filter_type": "category_filter", "value": "mexican"],
                ["title" : "Middle Eastern", "filter_type": "category_filter", "value": "mideastern"],
                ["title" : "Milk Bars", "filter_type": "category_filter", "value": "milkbars"],
                ["title" : "Modern Australian", "filter_type": "category_filter", "value": "modern_australian"],
                ["title" : "Modern European", "filter_type": "category_filter", "value": "modern_european"],
                ["title" : "Mongolian", "filter_type": "category_filter", "value": "mongolian"],
                ["title" : "Moroccan", "filter_type": "category_filter", "value": "moroccan"],
                ["title" : "New Zealand", "filter_type": "category_filter", "value": "newzealand"],
                ["title" : "Night Food", "filter_type": "category_filter", "value": "nightfood"],
                ["title" : "Norcinerie", "filter_type": "category_filter", "value": "norcinerie"],
                ["title" : "Open Sandwiches", "filter_type": "category_filter", "value": "opensandwiches"],
                ["title" : "Oriental", "filter_type": "category_filter", "value": "oriental"],
                ["title" : "Pakistani", "filter_type": "category_filter", "value": "pakistani"],
                ["title" : "Parent Cafes", "filter_type": "category_filter", "value": "eltern_cafes"],
                ["title" : "Parma", "filter_type": "category_filter", "value": "parma"],
                ["title" : "Persian/Iranian", "filter_type": "category_filter", "value": "persian"],
                ["title" : "Peruvian", "filter_type": "category_filter", "value": "peruvian"],
                ["title" : "Pita", "filter_type": "category_filter", "value": "pita"],
                ["title" : "Pizza", "filter_type": "category_filter", "value": "pizza"],
                ["title" : "Polish", "filter_type": "category_filter", "value": "polish"],
                ["title" : "Portuguese", "filter_type": "category_filter", "value": "portuguese"],
                ["title" : "Potatoes", "filter_type": "category_filter", "value": "potatoes"],
                ["title" : "Poutineries", "filter_type": "category_filter", "value": "poutineries"],
                ["title" : "Pub Food", "filter_type": "category_filter", "value": "pubfood"],
                ["title" : "Rice", "filter_type": "category_filter", "value": "riceshop"],
                ["title" : "Romanian", "filter_type": "category_filter", "value": "romanian"],
                ["title" : "Rotisserie Chicken", "filter_type": "category_filter", "value": "rotisserie_chicken"],
                ["title" : "Rumanian", "filter_type": "category_filter", "value": "rumanian"],
                ["title" : "Russian", "filter_type": "category_filter", "value": "russian"],
                ["title" : "Salad", "filter_type": "category_filter", "value": "salad"],
                ["title" : "Sandwiches", "filter_type": "category_filter", "value": "sandwiches"],
                ["title" : "Scandinavian", "filter_type": "category_filter", "value": "scandinavian"],
                ["title" : "Scottish", "filter_type": "category_filter", "value": "scottish"],
                ["title" : "Seafood", "filter_type": "category_filter", "value": "seafood"],
                ["title" : "Serbo Croatian", "filter_type": "category_filter", "value": "serbocroatian"],
                ["title" : "Signature Cuisine", "filter_type": "category_filter", "value": "signature_cuisine"],
                ["title" : "Singaporean", "filter_type": "category_filter", "value": "singaporean"],
                ["title" : "Slovakian", "filter_type": "category_filter", "value": "slovakian"],
                ["title" : "Soul Food", "filter_type": "category_filter", "value": "soulfood"],
                ["title" : "Soup", "filter_type": "category_filter", "value": "soup"],
                ["title" : "Southern", "filter_type": "category_filter", "value": "southern"],
                ["title" : "Spanish", "filter_type": "category_filter", "value": "spanish"],
                ["title" : "Steakhouses", "filter_type": "category_filter", "value": "steak"],
                ["title" : "Sushi Bars", "filter_type": "category_filter", "value": "sushi"],
                ["title" : "Swabian", "filter_type": "category_filter", "value": "swabian"],
                ["title" : "Swedish", "filter_type": "category_filter", "value": "swedish"],
                ["title" : "Swiss Food", "filter_type": "category_filter", "value": "swissfood"],
                ["title" : "Tabernas", "filter_type": "category_filter", "value": "tabernas"],
                ["title" : "Taiwanese", "filter_type": "category_filter", "value": "taiwanese"],
                ["title" : "Tapas Bars", "filter_type": "category_filter", "value": "tapas"],
                ["title" : "Tapas/Small Plates", "filter_type": "category_filter", "value": "tapasmallplates"],
                ["title" : "Tex-Mex", "filter_type": "category_filter", "value": "tex-mex"],
                ["title" : "Thai", "filter_type": "category_filter", "value": "thai"],
                ["title" : "Traditional Norwegian", "filter_type": "category_filter", "value": "norwegian"],
                ["title" : "Traditional Swedish", "filter_type": "category_filter", "value": "traditional_swedish"],
                ["title" : "Trattorie", "filter_type": "category_filter", "value": "trattorie"],
                ["title" : "Turkish", "filter_type": "category_filter", "value": "turkish"],
                ["title" : "Ukrainian", "filter_type": "category_filter", "value": "ukrainian"],
                ["title" : "Uzbek", "filter_type": "category_filter", "value": "uzbek"],
                ["title" : "Vegan", "filter_type": "category_filter", "value": "vegan"],
                ["title" : "Vegetarian", "filter_type": "category_filter", "value": "vegetarian"],
                ["title" : "Venison", "filter_type": "category_filter", "value": "venison"],
                ["title" : "titlese", "filter_type": "category_filter", "value": "titlese"],
                ["title" : "Wok", "filter_type": "category_filter", "value": "wok"],
                ["title" : "Wraps", "filter_type": "category_filter", "value": "wraps"],
                ["title" : "Yugoslav", "filter_type": "category_filter", "value": "yugoslav"]]
    }
}
