//
//  Category.swift
//  Yelp
//
//  Created by Josh Jeong on 4/7/17.
//  Copyright © 2017 Timothy Lee. All rights reserved.
//

import Foundation

class Category {
    
    func getList() -> [[String:String]] {
        return [["alias": "3dprinting", "title": "3D Printing"],
                ["alias": "abruzzese", "title": "Abruzzese"],
                ["alias": "absinthebars", "title": "Absinthe Bars"],
                ["alias": "acaibowls", "title": "Acai Bowls"],
                ["alias": "accessories", "title": "Accessories"],
                ["alias": "accountants", "title": "Accountants"],
                ["alias": "acnetreatment", "title": "Acne Treatment"],
                ["alias": "active", "title": "Active Life"],
                ["alias": "acupuncture", "title": "Acupuncture"],
                ["alias": "addictionmedicine", "title": "Addiction Medicine"],
                ["alias": "adoptionservices", "title": "Adoption Services"],
                ["alias": "adult", "title": "Adult"],
                ["alias": "adultedu", "title": "Adult Education"],
                ["alias": "adultentertainment", "title": "Adult Entertainment"],
                ["alias": "advertising", "title": "Advertising"],
                ["alias": "aerialfitness", "title": "Aerial Fitness"],
                ["alias": "aerialtours", "title": "Aerial Tours"],
                ["alias": "afghani", "title": "Afghan"],
                ["alias": "african", "title": "African"],
                ["alias": "afrobrazilian", "title": "Afro-Brazilian"],
                ["alias": "agriturismi", "title": "Agriturismi"],
                ["alias": "aircraftdealers", "title": "Aircraft Dealers"],
                ["alias": "aircraftrepairs", "title": "Aircraft Repairs"],
                ["alias": "airductcleaning", "title": "Air Duct Cleaning"],
                ["alias": "airlines", "title": "Airlines"],
                ["alias": "airport_shuttles", "title": "Airport Shuttles"],
                ["alias": "airportlounges", "title": "Airport Lounges"],
                ["alias": "airports", "title": "Airports"],
                ["alias": "airportterminals", "title": "Airport Terminals"],
                ["alias": "airsoft", "title": "Airsoft"],
                ["alias": "alentejo", "title": "Alentejo"],
                ["alias": "algarve", "title": "Algarve"],
                ["alias": "allergist", "title": "Allergists"],
                ["alias": "alsatian", "title": "Alsatian"],
                ["alias": "altoatesine", "title": "Altoatesine"],
                ["alias": "amateursportsteams", "title": "Amateur Sports Teams"],
                ["alias": "amusementparks", "title": "Amusement Parks"],
                ["alias": "andalusian", "title": "Andalusian"],
                ["alias": "anesthesiologists", "title": "Anesthesiologists"],
                ["alias": "animalholistic", "title": "Holistic Animal Care"],
                ["alias": "animalphysicaltherapy", "title": "Animal Physical Therapy"],
                ["alias": "animalshelters", "title": "Animal Shelters"],
                ["alias": "antiques", "title": "Antiques"],
                ["alias": "apartments", "title": "Apartments"],
                ["alias": "appliances", "title": "Appliances"],
                ["alias": "appraisalservices", "title": "Appraisal Services"],
                ["alias": "apulian", "title": "Apulian"],
                ["alias": "aquariums", "title": "Aquariums"],
                ["alias": "aquariumservices", "title": "Aquarium Services"],
                ["alias": "arabian", "title": "Arabian"],
                ["alias": "arabpizza", "title": "Arab Pizza"],
                ["alias": "arcades", "title": "Arcades"],
                ["alias": "archery", "title": "Archery"],
                ["alias": "architects", "title": "Architects"],
                ["alias": "architecturaltours", "title": "Architectural Tours"],
                ["alias": "argentine", "title": "Argentine"],
                ["alias": "armenian", "title": "Armenian"],
                ["alias": "arroceria_paella", "title": "Arroceria / Paella"],
                ["alias": "artclasses", "title": "Art Classes"],
                ["alias": "artificialturf", "title": "Artificial Turf"],
                ["alias": "artmuseums", "title": "Art Museums"],
                ["alias": "artrestoration", "title": "Art Restoration"],
                ["alias": "arts", "title": "Arts & Entertainment"],
                ["alias": "artsandcrafts", "title": "Arts & Crafts"],
                ["alias": "artschools", "title": "Art Schools"],
                ["alias": "artspacerentals", "title": "Art Space Rentals"],
                ["alias": "artsupplies", "title": "Art Supplies"],
                ["alias": "arttours", "title": "Art Tours"],
                ["alias": "asianfusion", "title": "Asian Fusion"],
                ["alias": "assistedliving", "title": "Assisted Living Facilities"],
                ["alias": "asturian", "title": "Asturian"],
                ["alias": "ateliers", "title": "Ateliers"],
                ["alias": "attractionfarms", "title": "Attraction Farms"],
                ["alias": "atvrentals", "title": "ATV Rentals/Tours"],
                ["alias": "auctionhouses", "title": "Auction Houses"],
                ["alias": "audiologist", "title": "Audiologist"],
                ["alias": "australian", "title": "Australian"],
                ["alias": "austrian", "title": "Austrian"],
                ["alias": "authorized_postal_representative", "title": "Authorized Postal Representative"],
                ["alias": "auto", "title": "Automotive"],
                ["alias": "auto_detailing", "title": "Auto Detailing"],
                ["alias": "autocustomization", "title": "Auto Customization"],
                ["alias": "autodamageassessment", "title": "Car Inspectors"],
                ["alias": "autoelectric", "title": "Auto Electric Services"],
                ["alias": "autoglass", "title": "Auto Glass Services"],
                ["alias": "autoinsurance", "title": "Auto Insurance"],
                ["alias": "autoloanproviders", "title": "Auto Loan Providers"],
                ["alias": "autopartssupplies", "title": "Auto Parts & Supplies"],
                ["alias": "autorepair", "title": "Auto Repair"],
                ["alias": "autosecurity", "title": "Auto Security"],
                ["alias": "autoupholstery", "title": "Auto Upholstery"],
                ["alias": "auvergnat", "title": "Auvergnat"],
                ["alias": "awnings", "title": "Awnings"],
                ["alias": "ayurveda", "title": "Ayurveda"],
                ["alias": "azores", "title": "Azores"],
                ["alias": "baby_gear", "title": "Baby Gear & Furniture"],
                ["alias": "backflowservices", "title": "Backflow Services"],
                ["alias": "backshop", "title": "Backshop"],
                ["alias": "baden", "title": "Baden"],
                ["alias": "badminton", "title": "Badminton"],
                ["alias": "bagels", "title": "Bagels"],
                ["alias": "baguettes", "title": "Baguettes"],
                ["alias": "bailbondsmen", "title": "Bail Bondsmen"],
                ["alias": "bakeries", "title": "Bakeries"],
                ["alias": "bangladeshi", "title": "Bangladeshi"],
                ["alias": "bankruptcy", "title": "Bankruptcy Law"],
                ["alias": "banks", "title": "Banks & Credit Unions"],
                ["alias": "barbers", "title": "Barbers"],
                ["alias": "barcrawl", "title": "Bar Crawl"],
                ["alias": "barreclasses", "title": "Barre Classes"],
                ["alias": "bars", "title": "Bars"],
                ["alias": "bartenders", "title": "Bartenders"],
                ["alias": "bartendingschools", "title": "Bartending Schools"],
                ["alias": "baseballfields", "title": "Baseball Fields"],
                ["alias": "basketballcourts", "title": "Basketball Courts"],
                ["alias": "basque", "title": "Basque"],
                ["alias": "bathing_area", "title": "Bathing Area"],
                ["alias": "batterystores", "title": "Battery Stores"],
                ["alias": "battingcages", "title": "Batting Cages"],
                ["alias": "bavarian", "title": "Bavarian"],
                ["alias": "bbq", "title": "Barbeque"],
                ["alias": "beachbars", "title": "Beach Bars"],
                ["alias": "beachequipmentrental", "title": "Beach Equipment Rentals"],
                ["alias": "beaches", "title": "Beaches"],
                ["alias": "beachvolleyball", "title": "Beach Volleyball"],
                ["alias": "beautysvc", "title": "Beauty & Spas"],
                ["alias": "bedbreakfast", "title": "Bed & Breakfast"],
                ["alias": "beer_and_wine", "title": "Beer, Wine & Spirits"],
                ["alias": "beerbar", "title": "Beer Bar"],
                ["alias": "beergarden", "title": "Beer Garden"],
                ["alias": "beergardens", "title": "Beer Gardens"],
                ["alias": "beerhall", "title": "Beer Hall"],
                ["alias": "beertours", "title": "Beer Tours"],
                ["alias": "behavioranalysts", "title": "Behavior Analysts"],
                ["alias": "beira", "title": "Beira"],
                ["alias": "beisl", "title": "Beisl"],
                ["alias": "belgian", "title": "Belgian"],
                ["alias": "bento", "title": "Bento"],
                ["alias": "berrichon", "title": "Berrichon"],
                ["alias": "bespoke", "title": "Bespoke Clothing"],
                ["alias": "bettingcenters", "title": "Betting Centers"],
                ["alias": "beverage_stores", "title": "Beverage Store"],
                ["alias": "bicyclepaths", "title": "Bicycle Paths"],
                ["alias": "bicycles", "title": "Bicycles"],
                ["alias": "bike_repair_maintenance", "title": "Bike Repair/Maintenance"],
                ["alias": "bikeassociations", "title": "Bike Associations"],
                ["alias": "bikeparking", "title": "Bike Parking"],
                ["alias": "bikerentals", "title": "Bike Rentals"],
                ["alias": "bikerepair", "title": "Bike Repair"],
                ["alias": "bikes", "title": "Bikes"],
                ["alias": "bikesharing", "title": "Bike Sharing"],
                ["alias": "bikeshop", "title": "Bike Shop"],
                ["alias": "billingservices", "title": "Billing Services"],
                ["alias": "bingo", "title": "Bingo Halls"],
                ["alias": "birdshops", "title": "Bird Shops"],
                ["alias": "bistros", "title": "Bistros"],
                ["alias": "blacksea", "title": "Black Sea"],
                ["alias": "blinds", "title": "Shades & Blinds"],
                ["alias": "blooddonation", "title": "Blood & Plasma Donation Centers"],
                ["alias": "blowfish", "title": "Blowfish"],
                ["alias": "blowoutservices", "title": "Blow Dry/Out Services"],
                ["alias": "boatcharters", "title": "Boat Charters"],
                ["alias": "boatdealers", "title": "Boat Dealers"],
                ["alias": "boating", "title": "Boating"],
                ["alias": "boatrepair", "title": "Boat Repair"],
                ["alias": "boattours", "title": "Boat Tours"],
                ["alias": "bobsledding", "title": "Bobsledding"],
                ["alias": "bocceball", "title": "Bocce Ball"],
                ["alias": "bodyshops", "title": "Body Shops"],
                ["alias": "bookbinding", "title": "Bookbinding"],
                ["alias": "bookkeepers", "title": "Bookkeepers"],
                ["alias": "bookstores", "title": "Bookstores"],
                ["alias": "bootcamps", "title": "Boot Camps"],
                ["alias": "bourguignon", "title": "Bourguignon"],
                ["alias": "bowling", "title": "Bowling"],
                ["alias": "boxing", "title": "Boxing"],
                ["alias": "brasseries", "title": "Brasseries"],
                ["alias": "brazilian", "title": "Brazilian"],
                ["alias": "brazilianempanadas", "title": "Brazilian Empanadas"],
                ["alias": "brazilianjiujitsu", "title": "Brazilian Jiu-jitsu"],
                ["alias": "breakfast_brunch", "title": "Breakfast & Brunch"],
                ["alias": "breweries", "title": "Breweries"],
                ["alias": "brewingsupplies", "title": "Brewing Supplies"],
                ["alias": "bridal", "title": "Bridal"],
                ["alias": "british", "title": "British"],
                ["alias": "bubblesoccer", "title": "Bubble Soccer"],
                ["alias": "bubbletea", "title": "Bubble Tea"],
                ["alias": "buddhist_temples", "title": "Buddhist Temples"],
                ["alias": "buffets", "title": "Buffets"],
                ["alias": "buildingsupplies", "title": "Building Supplies"],
                ["alias": "bulgarian", "title": "Bulgarian"],
                ["alias": "bulkbilling", "title": "Bulk Billing"],
                ["alias": "bungeejumping", "title": "Bungee Jumping"],
                ["alias": "burgers", "title": "Burgers"],
                ["alias": "burmese", "title": "Burmese"],
                ["alias": "buses", "title": "Buses"],
                ["alias": "businessconsulting", "title": "Business Consulting"],
                ["alias": "businessfinancing", "title": "Business Financing"],
                ["alias": "businesslawyers", "title": "Business Law"],
                ["alias": "busrental", "title": "Bus Rental"],
                ["alias": "busstations", "title": "Bus Stations"],
                ["alias": "bustours", "title": "Bus Tours"],
                ["alias": "butcher", "title": "Butcher"],
                ["alias": "c_and_mh", "title": "Counseling & Mental Health"],
                ["alias": "cabaret", "title": "Cabaret"],
                ["alias": "cabinetry", "title": "Cabinetry"],
                ["alias": "cablecars", "title": "Cable Cars"],
                ["alias": "cafes", "title": "Cafes"],
                ["alias": "cafeteria", "title": "Cafeteria"],
                ["alias": "cajun", "title": "Cajun/Creole"],
                ["alias": "cakeshop", "title": "Patisserie/Cake Shop"],
                ["alias": "calabrian", "title": "Calabrian"],
                ["alias": "calligraphy", "title": "Calligraphy"],
                ["alias": "cambodian", "title": "Cambodian"],
                ["alias": "campgrounds", "title": "Campgrounds"],
                ["alias": "candy", "title": "Candy Stores"],
                ["alias": "cannabis_clinics", "title": "Cannabis Clinics"],
                ["alias": "cannabiscollective", "title": "Cannabis Collective"],
                ["alias": "cannabisdispensaries", "title": "Cannabis Dispensaries"],
                ["alias": "cannabisreferrals", "title": "Medical Cannabis Referrals"],
                ["alias": "cannabistours", "title": "Cannabis Tours"],
                ["alias": "canteen", "title": "Canteen"],
                ["alias": "cantonese", "title": "Cantonese"],
                ["alias": "car_dealers", "title": "Car Dealers"],
                ["alias": "carauctions", "title": "Car Auctions"],
                ["alias": "carbrokers", "title": "Car Brokers"],
                ["alias": "carbuyers", "title": "Car Buyers"],
                ["alias": "cardioclasses", "title": "Cardio Classes"],
                ["alias": "cardiology", "title": "Cardiologists"],
                ["alias": "careercounseling", "title": "Career Counseling"],
                ["alias": "caribbean", "title": "Caribbean"],
                ["alias": "caricatures", "title": "Caricatures"],
                ["alias": "carousels", "title": "Carousels"],
                ["alias": "carpenters", "title": "Carpenters"],
                ["alias": "carpet_cleaning", "title": "Carpet Cleaning"],
                ["alias": "carpeting", "title": "Carpeting"],
                ["alias": "carpetinstallation", "title": "Carpet Installation"],
                ["alias": "carrental", "title": "Car Rental"],
                ["alias": "carshares", "title": "Car Share Services"],
                ["alias": "carwash", "title": "Car Wash"],
                ["alias": "carwindowtinting", "title": "Car Window Tinting"],
                ["alias": "casinos", "title": "Casinos"],
                ["alias": "castles", "title": "Castles"],
                ["alias": "catalan", "title": "Catalan"],
                ["alias": "catering", "title": "Caterers"],
                ["alias": "cellphoneaccessories", "title": "Mobile Phone Accessories"],
                ["alias": "centralbrazilian", "title": "Central Brazilian"],
                ["alias": "ceremonialclothing", "title": "Ceremonial Clothing"],
                ["alias": "challengecourses", "title": "Challenge Courses"],
                ["alias": "champagne_bars", "title": "Champagne Bars"],
                ["alias": "cheekufta", "title": "Chee Kufta"],
                ["alias": "cheese", "title": "Cheese Shops"],
                ["alias": "cheesesteaks", "title": "Cheesesteaks"],
                ["alias": "cheesetastingclasses", "title": "Cheese Tasting Classes"],
                ["alias": "chicken_wings", "title": "Chicken Wings"],
                ["alias": "chickenshop", "title": "Chicken Shop"],
                ["alias": "childbirthedu", "title": "Childbirth Education"],
                ["alias": "childcare", "title": "Child Care & Day Care"],
                ["alias": "childcloth", "title": "Children's Clothing"],
                ["alias": "childproofing", "title": "Childproofing"],
                ["alias": "childrensmuseums", "title": "Children's Museums"],
                ["alias": "chilean", "title": "Chilean"],
                ["alias": "chimneycakes", "title": "Chimney Cakes"],
                ["alias": "chimneysweeps", "title": "Chimney Sweeps"],
                ["alias": "chinese", "title": "Chinese"],
                ["alias": "chinesebazaar", "title": "Chinese Bazaar"],
                ["alias": "chinesemartialarts", "title": "Chinese Martial Arts"],
                ["alias": "chiropractors", "title": "Chiropractors"],
                ["alias": "chocolate", "title": "Chocolatiers & Shops"],
                ["alias": "choirs", "title": "Choirs"],
                ["alias": "christmastrees", "title": "Christmas Trees"],
                ["alias": "churches", "title": "Churches"],
                ["alias": "churros", "title": "Churros"],
                ["alias": "cideries", "title": "Cideries"],
                ["alias": "circuittraininggyms", "title": "Circuit Training Gyms"],
                ["alias": "circusschools", "title": "Circus Schools"],
                ["alias": "civiccenter", "title": "Civic Center"],
                ["alias": "climbing", "title": "Climbing"],
                ["alias": "clockrepair", "title": "Clock Repair"],
                ["alias": "clothingrental", "title": "Clothing Rental"],
                ["alias": "clowns", "title": "Clowns"],
                ["alias": "clubcrawl", "title": "Club Crawl"],
                ["alias": "cocktailbars", "title": "Cocktail Bars"],
                ["alias": "coffee", "title": "Coffee & Tea"],
                ["alias": "coffeeroasteries", "title": "Coffee Roasteries"],
                ["alias": "coffeeshops", "title": "Coffeeshops"],
                ["alias": "coffeeteasupplies", "title": "Coffee & Tea Supplies"],
                ["alias": "collegecounseling", "title": "College Counseling"],
                ["alias": "collegeuniv", "title": "Colleges & Universities"],
                ["alias": "colombian", "title": "Colombian"],
                ["alias": "colonics", "title": "Colonics"],
                ["alias": "comedyclubs", "title": "Comedy Clubs"],
                ["alias": "comfortfood", "title": "Comfort Food"],
                ["alias": "comicbooks", "title": "Comic Books"],
                ["alias": "commercialrealestate", "title": "Commercial Real Estate"],
                ["alias": "commissionedartists", "title": "Commissioned Artists"],
                ["alias": "communitybookbox", "title": "Community Book Box"],
                ["alias": "communitycenters", "title": "Community Centers"],
                ["alias": "communitygardens", "title": "Community Gardens"],
                ["alias": "computers", "title": "Computers"],
                ["alias": "concept_shops", "title": "Concept Shops"],
                ["alias": "conciergemedicine", "title": "Concierge Medicine"],
                ["alias": "condominiums", "title": "Condominiums"],
                ["alias": "congee", "title": "Congee"],
                ["alias": "contractlaw", "title": "Contract Law"],
                ["alias": "contractors", "title": "Contractors"],
                ["alias": "convenience", "title": "Convenience Stores"],
                ["alias": "conveyorsushi", "title": "Conveyor Belt Sushi"],
                ["alias": "cookingclasses", "title": "Cooking Classes"],
                ["alias": "cookingschools", "title": "Cooking Schools"],
                ["alias": "copyshops", "title": "Printing Services"],
                ["alias": "corsican", "title": "Corsican"],
                ["alias": "cosmeticdentists", "title": "Cosmetic Dentists"],
                ["alias": "cosmetics", "title": "Cosmetics & Beauty Supply"],
                ["alias": "cosmeticsurgeons", "title": "Cosmetic Surgeons"],
                ["alias": "cosmetology_schools", "title": "Cosmetology Schools"],
                ["alias": "costumes", "title": "Costumes"],
                ["alias": "countertopinstall", "title": "Countertop Installation"],
                ["alias": "countryclubs", "title": "Country Clubs"],
                ["alias": "countrydancehalls", "title": "Country Dance Halls"],
                ["alias": "couriers", "title": "Couriers & Delivery Services"],
                ["alias": "courthouses", "title": "Courthouses"],
                ["alias": "cprclasses", "title": "CPR Classes"],
                ["alias": "craneservices", "title": "Crane Services"],
                ["alias": "cremationservices", "title": "Cremation Services"],
                ["alias": "creperies", "title": "Creperies"],
                ["alias": "criminaldefense", "title": "Criminal Defense Law"],
                ["alias": "cryotherapy", "title": "Cryotherapy"],
                ["alias": "csa", "title": "CSA"],
                ["alias": "cuban", "title": "Cuban"],
                ["alias": "cucinacampana", "title": "Cucina campana"],
                ["alias": "culturalcenter", "title": "Cultural Center"],
                ["alias": "cupcakes", "title": "Cupcakes"],
                ["alias": "currencyexchange", "title": "Currency Exchange"],
                ["alias": "currysausage", "title": "Curry Sausage"],
                ["alias": "customcakes", "title": "Custom Cakes"],
                ["alias": "custommerchandise", "title": "Customized Merchandise"],
                ["alias": "customsbrokers", "title": "Customs Brokers"],
                ["alias": "cyclingclasses", "title": "Cycling Classes"],
                ["alias": "cypriot", "title": "Cypriot"],
                ["alias": "czech", "title": "Czech"],
                ["alias": "czechslovakian", "title": "Czech/Slovakian"],
                ["alias": "dagashi", "title": "Dagashi"],
                ["alias": "damagerestoration", "title": "Damage Restoration"],
                ["alias": "dance_schools", "title": "Dance Schools"],
                ["alias": "danceclubs", "title": "Dance Clubs"],
                ["alias": "dancerestaurants", "title": "Dance Restaurants"],
                ["alias": "dancestudio", "title": "Dance Studios"],
                ["alias": "dancewear", "title": "Dance Wear"],
                ["alias": "danish", "title": "Danish"],
                ["alias": "datarecovery", "title": "Data Recovery"],
                ["alias": "daycamps", "title": "Day Camps"],
                ["alias": "debtrelief", "title": "Debt Relief Services"],
                ["alias": "decksrailing", "title": "Decks & Railing"],
                ["alias": "delicatessen", "title": "Delicatessen"],
                ["alias": "delis", "title": "Delis"],
                ["alias": "demolitionservices", "title": "Demolition Services"],
                ["alias": "dentalhygeiniststorefront", "title": "Storefront Clinics"],
                ["alias": "dentalhygienists", "title": "Dental Hygienists"],
                ["alias": "dentalhygienistsmobile", "title": "Mobile Clinics"],
                ["alias": "dentists", "title": "Dentists"],
                ["alias": "departmentsofmotorvehicles", "title": "Departments of Motor Vehicles"],
                ["alias": "deptstores", "title": "Department Stores"],
                ["alias": "dermatology", "title": "Dermatologists"],
                ["alias": "desserts", "title": "Desserts"],
                ["alias": "diagnosticimaging", "title": "Diagnostic Imaging"],
                ["alias": "diagnosticservices", "title": "Diagnostic Services"],
                ["alias": "dialysisclinics", "title": "Dialysis Clinics"],
                ["alias": "dietitians", "title": "Dietitians"],
                ["alias": "digitizingservices", "title": "Digitizing Services"],
                ["alias": "dimsum", "title": "Dim Sum"],
                ["alias": "diners", "title": "Diners"],
                ["alias": "dinnertheater", "title": "Dinner Theater"],
                ["alias": "discgolf", "title": "Disc Golf"],
                ["alias": "discountstore", "title": "Discount Store"],
                ["alias": "distilleries", "title": "Distilleries"],
                ["alias": "divebars", "title": "Dive Bars"],
                ["alias": "diveshops", "title": "Dive Shops"],
                ["alias": "diving", "title": "Diving"],
                ["alias": "divorce", "title": "Divorce & Family Law"],
                ["alias": "diyautoshop", "title": "DIY Auto Shop"],
                ["alias": "diyfood", "title": "Do-It-Yourself Food"],
                ["alias": "djs", "title": "DJs"],
                ["alias": "dog_parks", "title": "Dog Parks"],
                ["alias": "dogwalkers", "title": "Dog Walkers"],
                ["alias": "dolmusstation", "title": "Dolmus Station"],
                ["alias": "dominican", "title": "Dominican"],
                ["alias": "donairs", "title": "Donairs"],
                ["alias": "donburi", "title": "Donburi"],
                ["alias": "donuts", "title": "Donuts"],
                ["alias": "doorsales", "title": "Door Sales/Installation"],
                ["alias": "doulas", "title": "Doulas"],
                ["alias": "dramaschools", "title": "Drama Schools"],
                ["alias": "driveintheater", "title": "Drive-In Theater"],
                ["alias": "drivethrubars", "title": "Drive-Thru Bars"],
                ["alias": "driving_schools", "title": "Driving Schools"],
                ["alias": "drugstores", "title": "Drugstores"],
                ["alias": "dryclean", "title": "Dry Cleaning"],
                ["alias": "drycleaninglaundry", "title": "Dry Cleaning & Laundry"],
                ["alias": "drywall", "title": "Drywall Installation & Repair"],
                ["alias": "duilawyers", "title": "DUI Law"],
                ["alias": "duischools", "title": "DUI Schools"],
                ["alias": "dumplings", "title": "Dumplings"],
                ["alias": "dumpsterrental", "title": "Dumpster Rental"],
                ["alias": "duplicationservices", "title": "Duplication Services"],
                ["alias": "dutyfreeshops", "title": "Duty-Free Shops"],
                ["alias": "earnosethroat", "title": "Ear Nose & Throat"],
                ["alias": "eastern_european", "title": "Eastern European"],
                ["alias": "easterngerman", "title": "Eastern German"],
                ["alias": "easternmexican", "title": "Eastern Mexican"],
                ["alias": "editorialservices", "title": "Editorial Services"],
                ["alias": "education", "title": "Education"],
                ["alias": "educationservices", "title": "Educational Services"],
                ["alias": "egyptian", "title": "Egyptian"],
                ["alias": "eldercareplanning", "title": "Elder Care Planning"],
                ["alias": "electricians", "title": "Electricians"],
                ["alias": "electronics", "title": "Electronics"],
                ["alias": "electronicsrepair", "title": "Electronics Repair"],
                ["alias": "elementaryschools", "title": "Elementary Schools"],
                ["alias": "eltern_cafes", "title": "Parent Cafes"],
                ["alias": "embassy", "title": "Embassy"],
                ["alias": "embroideryandcrochet", "title": "Embroidery & Crochet"],
                ["alias": "emergencymedicine", "title": "Emergency Medicine"],
                ["alias": "emergencypethospital", "title": "Emergency Pet Hospital"],
                ["alias": "emergencyrooms", "title": "Emergency Rooms"],
                ["alias": "emilian", "title": "Emilian"],
                ["alias": "empanadas", "title": "Empanadas"],
                ["alias": "employmentagencies", "title": "Employment Agencies"],
                ["alias": "employmentlawyers", "title": "Employment Law"],
                ["alias": "emstraining", "title": "EMS Training"],
                ["alias": "endocrinologists", "title": "Endocrinologists"],
                ["alias": "endodontists", "title": "Endodontists"],
                ["alias": "engraving", "title": "Engraving"],
                ["alias": "entertainmentlaw", "title": "Entertainment Law"],
                ["alias": "enviroabatement", "title": "Environmental Abatement"],
                ["alias": "environmentaltesting", "title": "Environmental Testing"],
                ["alias": "eroticmassage", "title": "Erotic Massage"],
                ["alias": "escapegames", "title": "Escape Games"],
                ["alias": "estateliquidation", "title": "Estate Liquidation"],
                ["alias": "estatephotography", "title": "Real Estate Photography"],
                ["alias": "estateplanning", "title": "Estate Planning Law"],
                ["alias": "ethicgrocery", "title": "Ethic Grocery"],
                ["alias": "ethiopian", "title": "Ethiopian"],
                ["alias": "evchargingstations", "title": "EV Charging Stations"],
                ["alias": "eventphotography", "title": "Event Photography"],
                ["alias": "eventplanning", "title": "Party & Event Planning"],
                ["alias": "eventservices", "title": "Event Planning & Services"],
                ["alias": "experiences", "title": "Experiences"],
                ["alias": "eyebrowservices", "title": "Eyebrow Services"],
                ["alias": "eyelashservice", "title": "Eyelash Service"],
                ["alias": "fabricstores", "title": "Fabric Stores"],
                ["alias": "facepainting", "title": "Face Painting"],
                ["alias": "fado_houses", "title": "Fado Houses"],
                ["alias": "falafel", "title": "Falafel"],
                ["alias": "familydr", "title": "Family Practice"],
                ["alias": "farmequipmentrepair", "title": "Farm Equipment Repair"],
                ["alias": "farmersmarket", "title": "Farmers Market"],
                ["alias": "farmingequipment", "title": "Farming Equipment"],
                ["alias": "farms", "title": "Farms"],
                ["alias": "farriers", "title": "Farriers"],
                ["alias": "fashion", "title": "Fashion"],
                ["alias": "fasil", "title": "Fasil Music"],
                ["alias": "fencesgates", "title": "Fences & Gates"],
                ["alias": "fencing", "title": "Fencing Clubs"],
                ["alias": "fengshui", "title": "Feng Shui"],
                ["alias": "ferries", "title": "Ferries"],
                ["alias": "fertility", "title": "Fertility"],
                ["alias": "festivals", "title": "Festivals"],
                ["alias": "filipino", "title": "Filipino"],
                ["alias": "financialadvising", "title": "Financial Advising"],
                ["alias": "financialservices", "title": "Financial Services"],
                ["alias": "fingerprinting", "title": "Fingerprinting"],
                ["alias": "firearmtraining", "title": "Firearm Training"],
                ["alias": "firedepartments", "title": "Fire Departments"],
                ["alias": "fireplace", "title": "Fireplace Services"],
                ["alias": "fireprotection", "title": "Fire Protection Services"],
                ["alias": "firewood", "title": "Firewood"],
                ["alias": "fireworks", "title": "Fireworks"],
                ["alias": "firstaidclasses", "title": "First Aid Classes"],
                ["alias": "fischbroetchen", "title": "Fischbroetchen"],
                ["alias": "fishing", "title": "Fishing"],
                ["alias": "fishmonger", "title": "Fishmonger"],
                ["alias": "fishnchips", "title": "Fish & Chips"],
                ["alias": "fitness", "title": "Fitness & Instruction"],
                ["alias": "fitnessequipment", "title": "Fitness/Exercise Equipment"],
                ["alias": "flatbread", "title": "Flatbread"],
                ["alias": "fleamarkets", "title": "Flea Markets"],
                ["alias": "flemish", "title": "Flemish"],
                ["alias": "flightinstruction", "title": "Flight Instruction"],
                ["alias": "floatspa", "title": "Float Spa"],
                ["alias": "flooring", "title": "Flooring"],
                ["alias": "florists", "title": "Florists"],
                ["alias": "flowers", "title": "Flowers & Gifts"],
                ["alias": "flyboarding", "title": "Flyboarding"],
                ["alias": "fondue", "title": "Fondue"],
                ["alias": "food", "title": "Food"],
                ["alias": "food_court", "title": "Food Court"],
                ["alias": "foodbanks", "title": "Food Banks"],
                ["alias": "fooddeliveryservices", "title": "Food Delivery Services"],
                ["alias": "foodsafety", "title": "Food Safety Training"],
                ["alias": "foodstands", "title": "Food Stands"],
                ["alias": "foodtours", "title": "Food Tours"],
                ["alias": "foodtrucks", "title": "Food Trucks"],
                ["alias": "football", "title": "Soccer"],
                ["alias": "forestry", "title": "Forestry"],
                ["alias": "formalwear", "title": "Formal Wear"],
                ["alias": "framing", "title": "Framing"],
                ["alias": "freediving", "title": "Free Diving"],
                ["alias": "freiduria", "title": "Freiduria"],
                ["alias": "french", "title": "French"],
                ["alias": "friterie", "title": "Friterie"],
                ["alias": "friulan", "title": "Friulan"],
                ["alias": "frozenfood", "title": "Frozen Food"],
                ["alias": "fueldocks", "title": "Fuel Docks"],
                ["alias": "funeralservices", "title": "Funeral Services & Cemeteries"],
                ["alias": "funfair", "title": "Fun Fair"],
                ["alias": "furclothing", "title": "Fur Clothing"],
                ["alias": "furniture", "title": "Furniture Stores"],
                ["alias": "furnitureassembly", "title": "Furniture Assembly"],
                ["alias": "furniturerepair", "title": "Furniture Repair"],
                ["alias": "fuzhou", "title": "Fuzhou"],
                ["alias": "galician", "title": "Galician"],
                ["alias": "galleries", "title": "Art Galleries"],
                ["alias": "gametruckrental", "title": "Game Truck Rental"],
                ["alias": "garage_door_services", "title": "Garage Door Services"],
                ["alias": "gardeners", "title": "Gardeners"],
                ["alias": "gardening", "title": "Nurseries & Gardening"],
                ["alias": "gardens", "title": "Botanical Gardens"],
                ["alias": "gastroenterologist", "title": "Gastroenterologist"],
                ["alias": "gastropubs", "title": "Gastropubs"],
                ["alias": "gaybars", "title": "Gay Bars"],
                ["alias": "gelato", "title": "Gelato"],
                ["alias": "general_litigation", "title": "General Litigation"],
                ["alias": "generaldentistry", "title": "General Dentistry"],
                ["alias": "generalfestivals", "title": "General Festivals"],
                ["alias": "generatorinstallrepair", "title": "Generator Installation/Repair"],
                ["alias": "geneticists", "title": "Geneticists"],
                ["alias": "georgian", "title": "Georgian"],
                ["alias": "german", "title": "German"],
                ["alias": "gerontologist", "title": "Gerontologists"],
                ["alias": "gestorias", "title": "Gestorias"],
                ["alias": "giblets", "title": "Giblets"],
                ["alias": "giftshops", "title": "Gift Shops"],
                ["alias": "glassandmirrors", "title": "Glass & Mirrors"],
                ["alias": "gliding", "title": "Gliding"],
                ["alias": "gluhwein", "title": "Mulled Wine"],
                ["alias": "gluten_free", "title": "Gluten-Free"],
                ["alias": "gokarts", "title": "Go Karts"],
                ["alias": "goldbuyers", "title": "Gold Buyers"],
                ["alias": "golf", "title": "Golf"],
                ["alias": "golfcartrentals", "title": "Golf Cart Rentals"],
                ["alias": "golfequipment", "title": "Golf Equipment"],
                ["alias": "golflessons", "title": "Golf Lessons"],
                ["alias": "gourmet", "title": "Specialty Food"],
                ["alias": "gozleme", "title": "Gozleme"],
                ["alias": "graphicdesign", "title": "Graphic Design"],
                ["alias": "greek", "title": "Greek"],
                ["alias": "grillingequipment", "title": "Grilling Equipment"],
                ["alias": "grocery", "title": "Grocery"],
                ["alias": "groomer", "title": "Pet Groomers"],
                ["alias": "guamanian", "title": "Guamanian"],
                ["alias": "guesthouses", "title": "Guest Houses"],
                ["alias": "guitarstores", "title": "Guitar Stores"],
                ["alias": "gun_ranges", "title": "Gun/Rifle Ranges"],
                ["alias": "guns_and_ammo", "title": "Guns & Ammo"],
                ["alias": "gutterservices", "title": "Gutter Services"],
                ["alias": "gymnastics", "title": "Gymnastics"],
                ["alias": "gyms", "title": "Gyms"],
                ["alias": "gyudon", "title": "Gyudon"],
                ["alias": "habilitativeservices", "title": "Habilitative Services"],
                ["alias": "hainan", "title": "Hainan"],
                ["alias": "hair", "title": "Hair Salons"],
                ["alias": "hair_extensions", "title": "Hair Extensions"],
                ["alias": "hairloss", "title": "Hair Loss Centers"],
                ["alias": "hairremoval", "title": "Hair Removal"],
                ["alias": "hairstylists", "title": "Hair Stylists"],
                ["alias": "haitian", "title": "Haitian"],
                ["alias": "hakka", "title": "Hakka"],
                ["alias": "halal", "title": "Halal"],
                ["alias": "halfwayhouses", "title": "Halfway Houses"],
                ["alias": "halotherapy", "title": "Halotherapy"],
                ["alias": "handball", "title": "Handball"],
                ["alias": "handrolls", "title": "Hand Rolls"],
                ["alias": "handyman", "title": "Handyman"],
                ["alias": "hanggliding", "title": "Hang Gliding"],
                ["alias": "hardware", "title": "Hardware Stores"],
                ["alias": "hats", "title": "Hats"],
                ["alias": "hauntedhouses", "title": "Haunted Houses"],
                ["alias": "hawaiian", "title": "Hawaiian"],
                ["alias": "hawkercentre", "title": "Hawker Centre"],
                ["alias": "hazardouswastedisposal", "title": "Hazardous Waste Disposal"],
                ["alias": "headshops", "title": "Head Shops"],
                ["alias": "health", "title": "Health & Medical"],
                ["alias": "healthinsurance", "title": "Health Insurance Offices"],
                ["alias": "healthmarkets", "title": "Health Markets"],
                ["alias": "healthretreats", "title": "Health Retreats"],
                ["alias": "healthtrainers", "title": "Trainers"],
                ["alias": "hearing_aids", "title": "Hearing Aids"],
                ["alias": "hearingaidproviders", "title": "Hearing Aid Providers"],
                ["alias": "henghwa", "title": "Henghwa"],
                ["alias": "hennaartists", "title": "Henna Artists"],
                ["alias": "hepatologists", "title": "Hepatologists"],
                ["alias": "herbalshops", "title": "Herbal Shops"],
                ["alias": "herbsandspices", "title": "Herbs & Spices"],
                ["alias": "hessian", "title": "Hessian"],
                ["alias": "heuriger", "title": "Heuriger"],
                ["alias": "hifi", "title": "High Fidelity Audio Equipment"],
                ["alias": "highschools", "title": "Middle Schools & High Schools"],
                ["alias": "hiking", "title": "Hiking"],
                ["alias": "himalayan", "title": "Himalayan/Nepalese"],
                ["alias": "hindu_temples", "title": "Hindu Temples"],
                ["alias": "historicaltours", "title": "Historical Tours"],
                ["alias": "hkcafe", "title": "Hong Kong Style Cafe"],
                ["alias": "hobbyshops", "title": "Hobby Shops"],
                ["alias": "hokkien", "title": "Hokkien"],
                ["alias": "holidaydecorations", "title": "Holiday Decorations"],
                ["alias": "home_inspectors", "title": "Home Inspectors"],
                ["alias": "home_organization", "title": "Home Organization"],
                ["alias": "homeandgarden", "title": "Home & Garden"],
                ["alias": "homeappliancerepair", "title": "Appliances & Repair"],
                ["alias": "homeautomation", "title": "Home Automation"],
                ["alias": "homecleaning", "title": "Home Cleaning"],
                ["alias": "homedecor", "title": "Home Decor"],
                ["alias": "homedevelopers", "title": "Home Developers"],
                ["alias": "homeenergyauditors", "title": "Home Energy Auditors"],
                ["alias": "homehealthcare", "title": "Home Health Care"],
                ["alias": "homeinsurance", "title": "Home & Rental Insurance"],
                ["alias": "homelessshelters", "title": "Homeless Shelters"],
                ["alias": "homemadefood", "title": "Homemade Food"],
                ["alias": "homenetworkinstall", "title": "Home Network Installation"],
                ["alias": "homeopathic", "title": "Homeopathic"],
                ["alias": "homeownerassociation", "title": "Homeowner Association"],
                ["alias": "homeservices", "title": "Home Services"],
                ["alias": "homestaging", "title": "Home Staging"],
                ["alias": "hometheatreinstallation", "title": "Home Theatre Installation"],
                ["alias": "homewindowtinting", "title": "Home Window Tinting"],
                ["alias": "honduran", "title": "Honduran"],
                ["alias": "honey", "title": "Honey"],
                ["alias": "hookah_bars", "title": "Hookah Bars"],
                ["alias": "horse_boarding", "title": "Horse Boarding"],
                ["alias": "horsebackriding", "title": "Horseback Riding"],
                ["alias": "horsequipment", "title": "Horse Equipment Shops"],
                ["alias": "horseracing", "title": "Horse Racing"],
                ["alias": "horumon", "title": "Horumon"],
                ["alias": "hospice", "title": "Hospice"],
                ["alias": "hospitalists", "title": "Hospitalists"],
                ["alias": "hospitals", "title": "Hospitals"],
                ["alias": "hostels", "title": "Hostels"],
                ["alias": "hot_air_balloons", "title": "Hot Air Balloons"],
                ["alias": "hotdog", "title": "Hot Dogs"],
                ["alias": "hotdogs", "title": "Fast Food"],
                ["alias": "hotel_bar", "title": "Hotel bar"],
                ["alias": "hotels", "title": "Hotels"],
                ["alias": "hotelstravel", "title": "Hotels & Travel"],
                ["alias": "hotpot", "title": "Hot Pot"],
                ["alias": "hotsprings", "title": "Hot Springs"],
                ["alias": "hottubandpool", "title": "Hot Tub & Pool"],
                ["alias": "housesitters", "title": "House Sitters"],
                ["alias": "housingcooperatives", "title": "Housing Cooperatives"],
                ["alias": "hunan", "title": "Hunan"],
                ["alias": "hungarian", "title": "Hungarian"],
                ["alias": "huntingfishingsupplies", "title": "Hunting & Fishing Supplies"],
                ["alias": "hvac", "title": "Heating & Air Conditioning/HVAC"],
                ["alias": "hydrojetting", "title": "Hydro-jetting"],
                ["alias": "hydroponics", "title": "Hydroponics"],
                ["alias": "hydrotherapy", "title": "Hydrotherapy"],
                ["alias": "hypnosis", "title": "Hypnosis/Hypnotherapy"],
                ["alias": "iberian", "title": "Iberian"],
                ["alias": "icecream", "title": "Ice Cream & Frozen Yogurt"],
                ["alias": "immigrationlawyers", "title": "Immigration Law"],
                ["alias": "immunodermatologists", "title": "Immunodermatologists"],
                ["alias": "importedfood", "title": "Imported Food"],
                ["alias": "indonesian", "title": "Indonesian"],
                ["alias": "indoor_playcenter", "title": "Indoor Playcentre"],
                ["alias": "indoorlandscaping", "title": "Indoor Landscaping"],
                ["alias": "indpak", "title": "Indian"],
                ["alias": "infectiousdisease", "title": "Infectious Disease Specialists"],
                ["alias": "installmentloans", "title": "Installment Loans"],
                ["alias": "insulationinstallation", "title": "Insulation Installation"],
                ["alias": "insurance", "title": "Insurance"],
                ["alias": "interiordesign", "title": "Interior Design"],
                ["alias": "internalmed", "title": "Internal Medicine"],
                ["alias": "international", "title": "International"],
                ["alias": "internetbooth", "title": "Internet Booths & Calling Centers"],
                ["alias": "internetcafe", "title": "Internet Cafes"],
                ["alias": "intervaltraininggyms", "title": "Interval Training Gyms"],
                ["alias": "intlgrocery", "title": "International Grocery"],
                ["alias": "investing", "title": "Investing"],
                ["alias": "iplaw", "title": "IP & Internet Law"],
                ["alias": "irish", "title": "Irish"],
                ["alias": "irish_pubs", "title": "Irish Pub"],
                ["alias": "irrigation", "title": "Irrigation"],
                ["alias": "island_pub", "title": "Island Pub"],
                ["alias": "isps", "title": "Internet Service Providers"],
                ["alias": "israeli", "title": "Israeli"],
                ["alias": "italian", "title": "Italian"],
                ["alias": "itservices", "title": "IT Services & Computer Repair"],
                ["alias": "ivhydration", "title": "IV Hydration"],
                ["alias": "izakaya", "title": "Izakaya"],
                ["alias": "jaliscan", "title": "Jaliscan"],
                ["alias": "japacurry", "title": "Japanese Curry"],
                ["alias": "japanese", "title": "Japanese"],
                ["alias": "jazzandblues", "title": "Jazz & Blues"],
                ["alias": "jetskis", "title": "Jet Skis"],
                ["alias": "jewelry", "title": "Jewelry"],
                ["alias": "jewelryrepair", "title": "Jewelry Repair"],
                ["alias": "jewish", "title": "Jewish"],
                ["alias": "jpsweets", "title": "Japanese Sweets"],
                ["alias": "juicebars", "title": "Juice Bars & Smoothies"],
                ["alias": "junkremovalandhauling", "title": "Junk Removal & Hauling"],
                ["alias": "junkyards", "title": "Junkyards"],
                ["alias": "kaiseki", "title": "Kaiseki"],
                ["alias": "karaoke", "title": "Karaoke"],
                ["alias": "karate", "title": "Karate"],
                ["alias": "kebab", "title": "Kebab"],
                ["alias": "kickboxing", "title": "Kickboxing"],
                ["alias": "kids_activities", "title": "Kids Activities"],
                ["alias": "kimonos", "title": "Kimonos"],
                ["alias": "kiosk", "title": "Kiosk"],
                ["alias": "kitchenandbath", "title": "Kitchen & Bath"],
                ["alias": "kitchenincubators", "title": "Kitchen Incubators"],
                ["alias": "kiteboarding", "title": "Kiteboarding"],
                ["alias": "knifesharpening", "title": "Knife Sharpening"],
                ["alias": "knittingsupplies", "title": "Knitting Supplies"],
                ["alias": "kombucha", "title": "Kombucha"],
                ["alias": "kopitiam", "title": "Kopitiam"],
                ["alias": "korean", "title": "Korean"],
                ["alias": "kosher", "title": "Kosher"],
                ["alias": "kurdish", "title": "Kurdish"],
                ["alias": "kushikatsu", "title": "Kushikatsu"],
                ["alias": "laboratorytesting", "title": "Laboratory Testing"],
                ["alias": "lactationservices", "title": "Lactation Services"],
                ["alias": "lahmacun", "title": "Lahmacun"],
                ["alias": "lakes", "title": "Lakes"],
                ["alias": "lancenters", "title": "LAN Centers"],
                ["alias": "landmarks", "title": "Landmarks & Historical Buildings"],
                ["alias": "landscapearchitects", "title": "Landscape Architects"],
                ["alias": "landscaping", "title": "Landscaping"],
                ["alias": "landsurveying", "title": "Land Surveying"],
                ["alias": "language_schools", "title": "Language Schools"],
                ["alias": "laos", "title": "Laos"],
                ["alias": "laotian", "title": "Laotian"],
                ["alias": "laser_hair_removal", "title": "Laser Hair Removal"],
                ["alias": "laserlasikeyes", "title": "Laser Eye Surgery/Lasik"],
                ["alias": "lasertag", "title": "Laser Tag"],
                ["alias": "latin", "title": "Latin American"],
                ["alias": "laundromat", "title": "Laundromat"],
                ["alias": "laundryservices", "title": "Laundry Services"],
                ["alias": "lawn_bowling", "title": "Lawn Bowling"],
                ["alias": "lawyers", "title": "Lawyers"],
                ["alias": "leather", "title": "Leather Goods"],
                ["alias": "lebanese", "title": "Lebanese"],
                ["alias": "legalservices", "title": "Legal Services"],
                ["alias": "leisure_centers", "title": "Leisure Centers"],
                ["alias": "libraries", "title": "Libraries"],
                ["alias": "liceservices", "title": "Lice Services"],
                ["alias": "lifecoach", "title": "Life Coach"],
                ["alias": "lifeinsurance", "title": "Life Insurance"],
                ["alias": "lighting", "title": "Lighting Fixtures & Equipment"],
                ["alias": "ligurian", "title": "Ligurian"],
                ["alias": "limos", "title": "Limos"],
                ["alias": "linens", "title": "Linens"],
                ["alias": "lingerie", "title": "Lingerie"],
                ["alias": "livestocksupply", "title": "Livestock Feed & Supply"],
                ["alias": "localfishstores", "title": "Local Fish Stores"],
                ["alias": "localflavor", "title": "Local Flavor"],
                ["alias": "localservices", "title": "Local Services"],
                ["alias": "locksmiths", "title": "Keys & Locksmiths"],
                ["alias": "lounges", "title": "Lounges"],
                ["alias": "luggage", "title": "Luggage"],
                ["alias": "luggagestorage", "title": "Luggage Storage"],
                ["alias": "lumbard", "title": "Lumbard"],
                ["alias": "lyonnais", "title": "Lyonnais"],
                ["alias": "macarons", "title": "Macarons"],
                ["alias": "machinerental", "title": "Machine & Tool Rental"],
                ["alias": "machineshops", "title": "Machine Shops"],
                ["alias": "madeira", "title": "Madeira"],
                ["alias": "magicians", "title": "Magicians"],
                ["alias": "mags", "title": "Newspapers & Magazines"],
                ["alias": "mahjong", "title": "Mah Jong Halls"],
                ["alias": "mailboxcenters", "title": "Mailbox Centers"],
                ["alias": "makeupartists", "title": "Makeup Artists"],
                ["alias": "malaysian", "title": "Malaysian"],
                ["alias": "mamak", "title": "Mamak"],
                ["alias": "marchingbands", "title": "Marching Bands"],
                ["alias": "marinas", "title": "Marinas"],
                ["alias": "marketing", "title": "Marketing"],
                ["alias": "markets", "title": "Fruits & Veggies"],
                ["alias": "marketstalls", "title": "Market Stalls"],
                ["alias": "martialarts", "title": "Martial Arts"],
                ["alias": "masonry_concrete", "title": "Masonry/Concrete"],
                ["alias": "massage", "title": "Massage"],
                ["alias": "massage_schools", "title": "Massage Schools"],
                ["alias": "massage_therapy", "title": "Massage Therapy"],
                ["alias": "massmedia", "title": "Mass Media"],
                ["alias": "matchmakers", "title": "Matchmakers"],
                ["alias": "materialeelettrico", "title": "Materiale elettrico"],
                ["alias": "maternity", "title": "Maternity Wear"],
                ["alias": "mattresses", "title": "Mattresses"],
                ["alias": "mauritius", "title": "Mauritius"],
                ["alias": "meatballs", "title": "Meatballs"],
                ["alias": "meats", "title": "Meat Shops"],
                ["alias": "medcenters", "title": "Medical Centers"],
                ["alias": "media", "title": "Books, Mags, Music & Video"],
                ["alias": "mediators", "title": "Mediators"],
                ["alias": "medicalfoot", "title": "Medical Foot Care"],
                ["alias": "medicallaw", "title": "Medical Law"],
                ["alias": "medicalspa", "title": "Medical Spas"],
                ["alias": "medicalsupplies", "title": "Medical Supplies"],
                ["alias": "medicaltransportation", "title": "Medical Transportation"],
                ["alias": "meditationcenters", "title": "Meditation Centers"],
                ["alias": "mediterranean", "title": "Mediterranean"],
                ["alias": "menscloth", "title": "Men's Clothing"],
                ["alias": "menshair", "title": "Men's Hair Salons"],
                ["alias": "metalfabricators", "title": "Metal Fabricators"],
                ["alias": "metrostations", "title": "Metro Stations"],
                ["alias": "mexican", "title": "Mexican"],
                ["alias": "mideastern", "title": "Middle Eastern"],
                ["alias": "midwives", "title": "Midwives"],
                ["alias": "milkbars", "title": "Milk Bars"],
                ["alias": "milkshakebars", "title": "Milkshake Bars"],
                ["alias": "minho", "title": "Minho"],
                ["alias": "mini_golf", "title": "Mini Golf"],
                ["alias": "mobiledentrepair", "title": "Mobile Dent Repair"],
                ["alias": "mobilehomes", "title": "Mobile Home Dealers"],
                ["alias": "mobileparks", "title": "Mobile Home Parks"],
                ["alias": "mobilephonerepair", "title": "Mobile Phone Repair"],
                ["alias": "mobilephones", "title": "Mobile Phones"],
                ["alias": "mobilityequipment", "title": "Mobility Equipment Sales & Services"],
                ["alias": "modern_australian", "title": "Modern Australian"],
                ["alias": "modern_european", "title": "Modern European"],
                ["alias": "mohels", "title": "Mohels"],
                ["alias": "mongolian", "title": "Mongolian"],
                ["alias": "montessori", "title": "Montessori Schools"],
                ["alias": "moroccan", "title": "Moroccan"],
                ["alias": "mortgagebrokers", "title": "Mortgage Brokers"],
                ["alias": "mortgagelenders", "title": "Mortgage Lenders"],
                ["alias": "mortuaryservices", "title": "Mortuary Services"],
                ["alias": "mosques", "title": "Mosques"],
                ["alias": "motodealers", "title": "Motorsport Vehicle Dealers"],
                ["alias": "motorcycle_rental", "title": "Motorcycle Rental"],
                ["alias": "motorcycledealers", "title": "Motorcycle Dealers"],
                ["alias": "motorcyclerepair", "title": "Motorcycle Repair"],
                ["alias": "motorcyclinggear", "title": "Motorcycle Gear"],
                ["alias": "motorepairs", "title": "Motorsport Vehicle Repairs"],
                ["alias": "mountainbiking", "title": "Mountain Biking"],
                ["alias": "mountainhuts", "title": "Mountain Huts"],
                ["alias": "movers", "title": "Movers"],
                ["alias": "movietheaters", "title": "Cinema"],
                ["alias": "muaythai", "title": "Muay Thai"],
                ["alias": "municipality", "title": "Municipality"],
                ["alias": "museums", "title": "Museums"],
                ["alias": "musicalinstrumentsandteachers", "title": "Musical Instruments & Teachers"],
                ["alias": "musicians", "title": "Musicians"],
                ["alias": "musicinstrumentservices", "title": "Musical Instrument Services"],
                ["alias": "musicproduction", "title": "Music Production Services"],
                ["alias": "musicvenues", "title": "Music Venues"],
                ["alias": "musicvideo", "title": "Music & DVDs"],
                ["alias": "nailtechnicians", "title": "Nail Technicians"],
                ["alias": "nannys", "title": "Nanny Services"],
                ["alias": "napoletana", "title": "Napoletana"],
                ["alias": "nasilemak", "title": "Nasi Lemak"],
                ["alias": "naturopathic", "title": "Naturopathic/Holistic"],
                ["alias": "nephrologists", "title": "Nephrologists"],
                ["alias": "neurologist", "title": "Neurologist"],
                ["alias": "neuropathologists", "title": "Neuropathologists"],
                ["alias": "neurotologists", "title": "Neurotologists"],
                ["alias": "newamerican", "title": "American (New)"],
                ["alias": "newcanadian", "title": "Canadian (New)"],
                ["alias": "newmexican", "title": "New Mexican Cuisine"],
                ["alias": "newzealand", "title": "New Zealand"],
                ["alias": "nicaraguan", "title": "Nicaraguan"],
                ["alias": "nicois", "title": "Nicoise"],
                ["alias": "nightfood", "title": "Night Food"],
                ["alias": "nightlife", "title": "Nightlife"],
                ["alias": "nikkei", "title": "Nikkei"],
                ["alias": "nonprofit", "title": "Community Service/Non-Profit"],
                ["alias": "noodles", "title": "Noodles"],
                ["alias": "norcinerie", "title": "Norcinerie"],
                ["alias": "northeasternbrazilian", "title": "Northeastern Brazilian"],
                ["alias": "northernbrazilian", "title": "Northern Brazilian"],
                ["alias": "northerngerman", "title": "Northern German"],
                ["alias": "northernmexican", "title": "Northern Mexican"],
                ["alias": "norwegian", "title": "Traditional Norwegian"],
                ["alias": "notaries", "title": "Notaries"],
                ["alias": "nudist", "title": "Nudist"],
                ["alias": "nursepractitioner", "title": "Nurse Practitioner"],
                ["alias": "nursingschools", "title": "Nursing Schools"],
                ["alias": "nutritionists", "title": "Nutritionists"],
                ["alias": "nyonya", "title": "Nyonya"],
                ["alias": "oaxacan", "title": "Oaxacan"],
                ["alias": "obgyn", "title": "Obstetricians & Gynecologists"],
                ["alias": "observatories", "title": "Observatories"],
                ["alias": "occupationaltherapy", "title": "Occupational Therapy"],
                ["alias": "oden", "title": "Oden"],
                ["alias": "officecleaning", "title": "Office Cleaning"],
                ["alias": "officeequipment", "title": "Office Equipment"],
                ["alias": "officiants", "title": "Officiants"],
                ["alias": "oilchange", "title": "Oil Change Stations"],
                ["alias": "okinawan", "title": "Okinawan"],
                ["alias": "okonomiyaki", "title": "Okonomiyaki"],
                ["alias": "oliveoil", "title": "Olive Oil"],
                ["alias": "oncologist", "title": "Oncologist"],
                ["alias": "onigiri", "title": "Onigiri"],
                ["alias": "opensandwiches", "title": "Open Sandwiches"],
                ["alias": "opera", "title": "Opera & Ballet"],
                ["alias": "opthamalogists", "title": "Ophthalmologists"],
                ["alias": "opticians", "title": "Eyewear & Opticians"],
                ["alias": "optometrists", "title": "Optometrists"],
                ["alias": "oralsurgeons", "title": "Oral Surgeons"],
                ["alias": "organdonorservices", "title": "Organ & Tissue Donor Services"],
                ["alias": "organic_stores", "title": "Organic Stores"],
                ["alias": "oriental", "title": "Oriental"],
                ["alias": "orthodontists", "title": "Orthodontists"],
                ["alias": "orthopedists", "title": "Orthopedists"],
                ["alias": "orthotics", "title": "Orthotics"],
                ["alias": "osteopathicphysicians", "title": "Osteopathic Physicians"],
                ["alias": "osteopaths", "title": "Osteopaths"],
                ["alias": "othersalons", "title": "Nail Salons"],
                ["alias": "otologists", "title": "Otologists"],
                ["alias": "ottomancuisine", "title": "Ottoman Cuisine"],
                ["alias": "outdoorfurniture", "title": "Outdoor Furniture Stores"],
                ["alias": "outdoorgear", "title": "Outdoor Gear"],
                ["alias": "outdoormovies", "title": "Outdoor Movies"],
                ["alias": "outlet_stores", "title": "Outlet Stores"],
                ["alias": "oxygenbars", "title": "Oxygen Bars"],
                ["alias": "oyakodon", "title": "Oyakodon"],
                ["alias": "pachinko", "title": "Pachinko"],
                ["alias": "packingservices", "title": "Packing Services"],
                ["alias": "packingsupplies", "title": "Packing Supplies"],
                ["alias": "paddleboarding", "title": "Paddleboarding"],
                ["alias": "painmanagement", "title": "Pain Management"],
                ["alias": "paintandsip", "title": "Paint & Sip"],
                ["alias": "paintball", "title": "Paintball"],
                ["alias": "painters", "title": "Painters"],
                ["alias": "paintstores", "title": "Paint Stores"],
                ["alias": "paintyourownpottery", "title": "Paint-Your-Own Pottery"],
                ["alias": "pakistani", "title": "Pakistani"],
                ["alias": "palatine", "title": "Palatine"],
                ["alias": "panasian", "title": "Pan Asian"],
                ["alias": "panzerotti", "title": "Panzerotti"],
                ["alias": "parasailing", "title": "Parasailing"],
                ["alias": "parentingclasses", "title": "Parenting Classes"],
                ["alias": "parking", "title": "Parking"],
                ["alias": "parklets", "title": "Parklets"],
                ["alias": "parks", "title": "Parks"],
                ["alias": "parma", "title": "Parma"],
                ["alias": "partybikerentals", "title": "Party Bike Rentals"],
                ["alias": "partybusrentals", "title": "Party Bus Rentals"],
                ["alias": "partycharacters", "title": "Party Characters"],
                ["alias": "partyequipmentrentals", "title": "Party Equipment Rentals"],
                ["alias": "partysupplies", "title": "Party Supplies"],
                ["alias": "passportvisaservices", "title": "Passport & Visa Services"],
                ["alias": "pastashops", "title": "Pasta Shops"],
                ["alias": "patentlaw", "title": "Patent Law"],
                ["alias": "pathologists", "title": "Pathologists"],
                ["alias": "patiocoverings", "title": "Patio Coverings"],
                ["alias": "pawn", "title": "Pawn Shops"],
                ["alias": "paydayloans", "title": "Check Cashing/Pay-day Loans"],
                ["alias": "payroll", "title": "Payroll Services"],
                ["alias": "pediatric_dentists", "title": "Pediatric Dentists"],
                ["alias": "pediatricians", "title": "Pediatricians"],
                ["alias": "pedicabs", "title": "Pedicabs"],
                ["alias": "pekinese", "title": "Pekinese"],
                ["alias": "pensions", "title": "Pensions"],
                ["alias": "perfume", "title": "Perfume"],
                ["alias": "periodontists", "title": "Periodontists"],
                ["alias": "permanentmakeup", "title": "Permanent Makeup"],
                ["alias": "persian", "title": "Persian/Iranian"],
                ["alias": "personal_injury", "title": "Personal Injury Law"],
                ["alias": "personal_shopping", "title": "Personal Shopping"],
                ["alias": "personalassistants", "title": "Personal Assistants"],
                ["alias": "personalcare", "title": "Personal Care Services"],
                ["alias": "personalchefs", "title": "Personal Chefs"],
                ["alias": "peruvian", "title": "Peruvian"],
                ["alias": "pest_control", "title": "Pest Control"],
                ["alias": "pet_sitting", "title": "Pet Boarding/Pet Sitting"],
                ["alias": "pet_training", "title": "Pet Training"],
                ["alias": "petadoption", "title": "Pet Adoption"],
                ["alias": "petbreeders", "title": "Pet Breeders"],
                ["alias": "petcremation", "title": "Pet Cremation Services"],
                ["alias": "pethospice", "title": "Pet Hospice"],
                ["alias": "petinsurance", "title": "Pet Insurance"],
                ["alias": "petphotography", "title": "Pet Photography"],
                ["alias": "pets", "title": "Pets"],
                ["alias": "petservices", "title": "Pet Services"],
                ["alias": "petstore", "title": "Pet Stores"],
                ["alias": "pettingzoos", "title": "Petting Zoos"],
                ["alias": "pettransport", "title": "Pet Transportation"],
                ["alias": "pfcomercial", "title": "PF/Comercial"],
                ["alias": "pharmacy", "title": "Pharmacy"],
                ["alias": "phlebologists", "title": "Phlebologists"],
                ["alias": "photoboothrentals", "title": "Photo Booth Rentals"],
                ["alias": "photographers", "title": "Photographers"],
                ["alias": "photographystores", "title": "Photography Stores & Services"],
                ["alias": "physicaltherapy", "title": "Physical Therapy"],
                ["alias": "physicians", "title": "Doctors"],
                ["alias": "piadina", "title": "Piadina"],
                ["alias": "pianobars", "title": "Piano Bars"],
                ["alias": "pianoservices", "title": "Piano Services"],
                ["alias": "pianostores", "title": "Piano Stores"],
                ["alias": "pickyourown", "title": "Pick Your Own Farms"],
                ["alias": "piemonte", "title": "Piemonte"],
                ["alias": "piercing", "title": "Piercing"],
                ["alias": "pierogis", "title": "Pierogis"],
                ["alias": "pilates", "title": "Pilates"],
                ["alias": "pita", "title": "Pita"],
                ["alias": "pizza", "title": "Pizza"],
                ["alias": "placentaencapsulation", "title": "Placenta Encapsulations"],
                ["alias": "planetarium", "title": "Planetarium"],
                ["alias": "playgrounds", "title": "Playgrounds"],
                ["alias": "playsets", "title": "Playsets"],
                ["alias": "plumbing", "title": "Plumbing"],
                ["alias": "plus_size_fashion", "title": "Plus Size Fashion"],
                ["alias": "podiatrists", "title": "Podiatrists"],
                ["alias": "poke", "title": "Poke"],
                ["alias": "poledancingclasses", "title": "Pole Dancing Classes"],
                ["alias": "policedepartments", "title": "Police Departments"],
                ["alias": "polish", "title": "Polish"],
                ["alias": "poolbilliards", "title": "Pool & Billiards"],
                ["alias": "poolcleaners", "title": "Pool Cleaners"],
                ["alias": "poolhalls", "title": "Pool Halls"],
                ["alias": "poolservice", "title": "Pool & Hot Tub Service"],
                ["alias": "popcorn", "title": "Popcorn Shops"],
                ["alias": "popuprestaurants", "title": "Pop-Up Restaurants"],
                ["alias": "popupshops", "title": "Pop-up Shops"],
                ["alias": "portuguese", "title": "Portuguese"],
                ["alias": "postoffices", "title": "Post Offices"],
                ["alias": "potatoes", "title": "Potatoes"],
                ["alias": "poutineries", "title": "Poutineries"],
                ["alias": "powdercoating", "title": "Powder Coating"],
                ["alias": "prenatal", "title": "Prenatal/Perinatal Care"],
                ["alias": "preschools", "title": "Preschools"],
                ["alias": "pressurewashers", "title": "Pressure Washers"],
                ["alias": "pretzels", "title": "Pretzels"],
                ["alias": "preventivemedicine", "title": "Preventive Medicine"],
                ["alias": "printmedia", "title": "Print Media"],
                ["alias": "privateinvestigation", "title": "Private Investigation"],
                ["alias": "privatejetcharter", "title": "Private Jet Charter"],
                ["alias": "privateschools", "title": "Private Schools"],
                ["alias": "privatetutors", "title": "Private Tutors"],
                ["alias": "processservers", "title": "Process Servers"],
                ["alias": "proctologist", "title": "Proctologists"],
                ["alias": "productdesign", "title": "Product Design"],
                ["alias": "professional", "title": "Professional Services"],
                ["alias": "propane", "title": "Propane"],
                ["alias": "propertymgmt", "title": "Property Management"],
                ["alias": "props", "title": "Props"],
                ["alias": "prosthetics", "title": "Prosthetics"],
                ["alias": "prosthodontists", "title": "Prosthodontists"],
                ["alias": "provencal", "title": "Provencal"],
                ["alias": "psychiatrists", "title": "Psychiatrists"],
                ["alias": "psychic_astrology", "title": "Psychics & Astrologers"],
                ["alias": "psychoanalysts", "title": "Psychoanalysts"],
                ["alias": "psychologists", "title": "Psychologists"],
                ["alias": "psychotechnicaltests", "title": "Psychotechnical Tests"],
                ["alias": "psychotherapists", "title": "Psychotherapists"],
                ["alias": "pubfood", "title": "Pub Food"],
                ["alias": "publicart", "title": "Public Art"],
                ["alias": "publicplazas", "title": "Public Plazas"],
                ["alias": "publicrelations", "title": "Public Relations"],
                ["alias": "publicservicesgovt", "title": "Public Services & Government"],
                ["alias": "publictransport", "title": "Public Transportation"],
                ["alias": "pubs", "title": "Pubs"],
                ["alias": "pueblan", "title": "Pueblan"],
                ["alias": "puertorican", "title": "Puerto Rican"],
                ["alias": "pulmonologist", "title": "Pulmonologist"],
                ["alias": "pulquerias", "title": "Pulquerias"],
                ["alias": "pumpkinpatches", "title": "Pumpkin Patches"],
                ["alias": "qigong", "title": "Qi Gong"],
                ["alias": "races", "title": "Races & Competitions"],
                ["alias": "racetracks", "title": "Race Tracks"],
                ["alias": "racingexperience", "title": "Racing Experience"],
                ["alias": "radiologists", "title": "Radiologists"],
                ["alias": "radiostations", "title": "Radio Stations"],
                ["alias": "rafting", "title": "Rafting/Kayaking"],
                ["alias": "ramen", "title": "Ramen"],
                ["alias": "ranches", "title": "Ranches"],
                ["alias": "raw_food", "title": "Live/Raw Food"],
                ["alias": "realestate", "title": "Real Estate"],
                ["alias": "realestateagents", "title": "Real Estate Agents"],
                ["alias": "realestatelawyers", "title": "Real Estate Law"],
                ["alias": "realestatesvcs", "title": "Real Estate Services"],
                ["alias": "record_labels", "title": "Record Labels"],
                ["alias": "recording_studios", "title": "Recording & Rehearsal Studios"],
                ["alias": "recreation", "title": "Recreation Centers"],
                ["alias": "recyclingcenter", "title": "Recycling Center"],
                ["alias": "refinishing", "title": "Refinishing Services"],
                ["alias": "reflexology", "title": "Reflexology"],
                ["alias": "registrationservices", "title": "Registration Services"],
                ["alias": "registry_office", "title": "Registry Office"],
                ["alias": "rehabilitation_center", "title": "Rehabilitation Center"],
                ["alias": "reiki", "title": "Reiki"],
                ["alias": "religiousitems", "title": "Religious Items"],
                ["alias": "religiousorgs", "title": "Religious Organizations"],
                ["alias": "religiousschools", "title": "Religious Schools"],
                ["alias": "rentfurniture", "title": "Furniture Rental"],
                ["alias": "reptileshops", "title": "Reptile Shops"],
                ["alias": "residences", "title": "Residences"],
                ["alias": "resorts", "title": "Resorts"],
                ["alias": "restaurants", "title": "Restaurants"],
                ["alias": "reststops", "title": "Rest Stops"],
                ["alias": "retirement_homes", "title": "Retirement Homes"],
                ["alias": "reunion", "title": "Reunion"],
                ["alias": "reupholstery", "title": "Furniture Reupholstery"],
                ["alias": "rhematologists", "title": "Rheumatologists"],
                ["alias": "rhinelandian", "title": "Rhinelandian"],
                ["alias": "ribatejo", "title": "Ribatejo"],
                ["alias": "riceshop", "title": "Rice"],
                ["alias": "roadsideassist", "title": "Roadside Assistance"],
                ["alias": "robatayaki", "title": "Robatayaki"],
                ["alias": "rock_climbing", "title": "Rock Climbing"],
                ["alias": "rodeo", "title": "Rodeo"],
                ["alias": "rodizios", "title": "Rodizios"],
                ["alias": "rolfing", "title": "Rolfing"],
                ["alias": "roman", "title": "Roman"],
                ["alias": "romanian", "title": "Romanian"],
                ["alias": "roofing", "title": "Roofing"],
                ["alias": "roofinspectors", "title": "Roof Inspectors"],
                ["alias": "rotisserie_chicken", "title": "Rotisserie Chicken"],
                ["alias": "rugs", "title": "Rugs"],
                ["alias": "rumanian", "title": "Rumanian"],
                ["alias": "russian", "title": "Russian"],
                ["alias": "rv_dealers", "title": "RV Dealers"],
                ["alias": "rvparks", "title": "RV Parks"],
                ["alias": "rvrental", "title": "RV Rental"],
                ["alias": "rvrepair", "title": "RV Repair"],
                ["alias": "ryokan", "title": "Ryokan"],
                ["alias": "safetyequipment", "title": "Safety Equipment"],
                ["alias": "sailing", "title": "Sailing"],
                ["alias": "sakebars", "title": "Sake Bars"],
                ["alias": "salad", "title": "Salad"],
                ["alias": "salumerie", "title": "Salumerie"],
                ["alias": "salvadoran", "title": "Salvadoran"],
                ["alias": "sambaschools", "title": "Samba Schools"],
                ["alias": "sandblasting", "title": "Sandblasting"],
                ["alias": "sandwiches", "title": "Sandwiches"],
                ["alias": "sardinian", "title": "Sardinian"],
                ["alias": "saunas", "title": "Saunas"],
                ["alias": "scandinavian", "title": "Scandinavian"],
                ["alias": "scandinaviandesign", "title": "Scandinavian Design"],
                ["alias": "scavengerhunts", "title": "Scavenger Hunts"],
                ["alias": "schnitzel", "title": "Schnitzel"],
                ["alias": "scootertours", "title": "Scooter Tours"],
                ["alias": "scottish", "title": "Scottish"],
                ["alias": "screen_printing_tshirt_printing", "title": "Screen Printing/T-Shirt Printing"],
                ["alias": "screenprinting", "title": "Screen Printing"],
                ["alias": "scuba", "title": "Scuba Diving"],
                ["alias": "seafood", "title": "Seafood"],
                ["alias": "seafoodmarkets", "title": "Seafood Markets"],
                ["alias": "seasonaldecorservices", "title": "Holiday Decorating Services"],
                ["alias": "security", "title": "Security Services"],
                ["alias": "securitysystems", "title": "Security Systems"],
                ["alias": "selfstorage", "title": "Self Storage"],
                ["alias": "senegalese", "title": "Senegalese"],
                ["alias": "seniorcenters", "title": "Senior Centers"],
                ["alias": "septicservices", "title": "Septic Services"],
                ["alias": "serbocroatian", "title": "Serbo Croatian"],
                ["alias": "servicestations", "title": "Gas & Service Stations"],
                ["alias": "sessionphotography", "title": "Session Photography"],
                ["alias": "sewingalterations", "title": "Sewing & Alterations"],
                ["alias": "sextherapists", "title": "Sex Therapists"],
                ["alias": "shanghainese", "title": "Shanghainese"],
                ["alias": "sharedofficespaces", "title": "Shared Office Spaces"],
                ["alias": "sharedtaxis", "title": "Shared Taxis"],
                ["alias": "shavedice", "title": "Shaved Ice"],
                ["alias": "shavedsnow", "title": "Shaved Snow"],
                ["alias": "shipping_centers", "title": "Shipping Centers"],
                ["alias": "shoerepair", "title": "Shoe Repair"],
                ["alias": "shoes", "title": "Shoe Stores"],
                ["alias": "shoeshine", "title": "Shoe Shine"],
                ["alias": "shopping", "title": "Shopping"],
                ["alias": "shoppingcenters", "title": "Shopping Centers"],
                ["alias": "shredding", "title": "Shredding Services"],
                ["alias": "shrines", "title": "Shrines"],
                ["alias": "shutters", "title": "Shutters"],
                ["alias": "sicilian", "title": "Sicilian"],
                ["alias": "signature_cuisine", "title": "Signature Cuisine"],
                ["alias": "signmaking", "title": "Signmaking"],
                ["alias": "silentdisco", "title": "Silent Disco"],
                ["alias": "singaporean", "title": "Singaporean"],
                ["alias": "skate_parks", "title": "Skate Parks"],
                ["alias": "skateshops", "title": "Skate Shops"],
                ["alias": "skatingrinks", "title": "Skating Rinks"],
                ["alias": "skiing", "title": "Skiing"],
                ["alias": "skillednursing", "title": "Skilled Nursing"],
                ["alias": "skincare", "title": "Skin Care"],
                ["alias": "skiresorts", "title": "Ski Resorts"],
                ["alias": "skischools", "title": "Ski Schools"],
                ["alias": "skishops", "title": "Ski & Snowboard Shops"],
                ["alias": "skydiving", "title": "Skydiving"],
                ["alias": "sledding", "title": "Sledding"],
                ["alias": "sleepspecialists", "title": "Sleep Specialists"],
                ["alias": "sleepwear", "title": "Sleepwear"],
                ["alias": "slovakian", "title": "Slovakian"],
                ["alias": "smog_check_stations", "title": "Smog Check Stations"],
                ["alias": "smokehouse", "title": "Smokehouse"],
                ["alias": "snorkeling", "title": "Snorkeling"],
                ["alias": "snowremoval", "title": "Snow Removal"],
                ["alias": "snuggleservices", "title": "Snuggle Services"],
                ["alias": "soba", "title": "Soba"],
                ["alias": "social_clubs", "title": "Social Clubs"],
                ["alias": "softwaredevelopment", "title": "Software Development"],
                ["alias": "solarinstallation", "title": "Solar Installation"],
                ["alias": "solarpanelcleaning", "title": "Solar Panel Cleaning"],
                ["alias": "sommelierservices", "title": "Sommelier Services"],
                ["alias": "sophrologists", "title": "Sophrologists"],
                ["alias": "soulfood", "title": "Soul Food"],
                ["alias": "soup", "title": "Soup"],
                ["alias": "southafrican", "title": "South African"],
                ["alias": "southern", "title": "Southern"],
                ["alias": "souvenirs", "title": "Souvenir Shops"],
                ["alias": "spanish", "title": "Spanish"],
                ["alias": "spas", "title": "Day Spas"],
                ["alias": "speakeasies", "title": "Speakeasies"],
                ["alias": "specialbikes", "title": "Special Bikes"],
                ["alias": "specialed", "title": "Special Education"],
                ["alias": "specialtyschools", "title": "Specialty Schools"],
                ["alias": "speech_therapists", "title": "Speech Therapists"],
                ["alias": "spermclinic", "title": "Sperm Clinic"],
                ["alias": "spinesurgeons", "title": "Spine Surgeons"],
                ["alias": "spiritism", "title": "Spiritism"],
                ["alias": "spiritual_shop", "title": "Spiritual Shop"],
                ["alias": "sport_equipment_hire", "title": "Sport Equipment Hire"],
                ["alias": "sportgoods", "title": "Sporting Goods"],
                ["alias": "sports_clubs", "title": "Sports Clubs"],
                ["alias": "sportsbars", "title": "Sports Bars"],
                ["alias": "sportsmed", "title": "Sports Medicine"],
                ["alias": "sportspsychologists", "title": "Sports Psychologists"],
                ["alias": "sportsteams", "title": "Professional Sports Teams"],
                ["alias": "sportswear", "title": "Sports Wear"],
                ["alias": "spraytanning", "title": "Spray Tanning"],
                ["alias": "squash", "title": "Squash"],
                ["alias": "srilankan", "title": "Sri Lankan"],
                ["alias": "stadiumsarenas", "title": "Stadiums & Arenas"],
                ["alias": "stationery", "title": "Cards & Stationery"],
                ["alias": "steak", "title": "Steakhouses"],
                ["alias": "stereo_installation", "title": "Car Stereo Installation"],
                ["alias": "stockings", "title": "Stockings"],
                ["alias": "streetart", "title": "Street Art"],
                ["alias": "streetvendors", "title": "Street Vendors"],
                ["alias": "structuralengineers", "title": "Structural Engineers"],
                ["alias": "stucco", "title": "Stucco Services"],
                ["alias": "studiotaping", "title": "Studio Taping"],
                ["alias": "sud_ouest", "title": "French Southwest"],
                ["alias": "sugaring", "title": "Sugaring"],
                ["alias": "sugarshacks", "title": "Sugar Shacks"],
                ["alias": "sukiyaki", "title": "Sukiyaki"],
                ["alias": "summer_camps", "title": "Summer Camps"],
                ["alias": "supperclubs", "title": "Supper Clubs"],
                ["alias": "suppliesrestaurant", "title": "Restaurant Supplies"],
                ["alias": "surfing", "title": "Surfing"],
                ["alias": "surflifesaving", "title": "Surf Lifesaving"],
                ["alias": "surfschools", "title": "Surf Schools"],
                ["alias": "surfshop", "title": "Surf Shop"],
                ["alias": "surgeons", "title": "Surgeons"],
                ["alias": "sushi", "title": "Sushi Bars"],
                ["alias": "swabian", "title": "Swabian"],
                ["alias": "swedish", "title": "Swedish"],
                ["alias": "swimminglessons", "title": "Swimming Lessons/Schools"],
                ["alias": "swimmingpools", "title": "Swimming Pools"],
                ["alias": "swimwear", "title": "Swimwear"],
                ["alias": "swissfood", "title": "Swiss Food"],
                ["alias": "synagogues", "title": "Synagogues"],
                ["alias": "syrian", "title": "Syrian"],
                ["alias": "szechuan", "title": "Szechuan"],
                ["alias": "tabac", "title": "Tabac"],
                ["alias": "tabernas", "title": "Tabernas"],
                ["alias": "tablaoflamenco", "title": "Tablao Flamenco"],
                ["alias": "tabletopgames", "title": "Tabletop Games"],
                ["alias": "tableware", "title": "Tableware"],
                ["alias": "tacos", "title": "Tacos"],
                ["alias": "taekwondo", "title": "Taekwondo"],
                ["alias": "taichi", "title": "Tai Chi"],
                ["alias": "taiwanese", "title": "Taiwanese"],
                ["alias": "taiyaki", "title": "Taiyaki"],
                ["alias": "takoyaki", "title": "Takoyaki"],
                ["alias": "talentagencies", "title": "Talent Agencies"],
                ["alias": "tamales", "title": "Tamales"],
                ["alias": "tanning", "title": "Tanning"],
                ["alias": "tanningbeds", "title": "Tanning Beds"],
                ["alias": "taoisttemples", "title": "Taoist Temples"],
                ["alias": "tapas", "title": "Tapas Bars"],
                ["alias": "tapasmallplates", "title": "Tapas/Small Plates"],
                ["alias": "tastingclasses", "title": "Tasting Classes"],
                ["alias": "tattoo", "title": "Tattoo"],
                ["alias": "tattooremoval", "title": "Tattoo Removal"],
                ["alias": "tavolacalda", "title": "Tavola Calda"],
                ["alias": "taxidermy", "title": "Taxidermy"],
                ["alias": "taxis", "title": "Taxis"],
                ["alias": "taxlaw", "title": "Tax Law"],
                ["alias": "taxoffice", "title": "Tax Office"],
                ["alias": "taxservices", "title": "Tax Services"],
                ["alias": "tcm", "title": "Traditional Chinese Medicine"],
                ["alias": "tea", "title": "Tea Rooms"],
                ["alias": "teachersupplies", "title": "Teacher Supplies"],
                ["alias": "teambuilding", "title": "Team Building Activities"],
                ["alias": "teethwhitening", "title": "Teeth Whitening"],
                ["alias": "telecommunications", "title": "Telecommunications"],
                ["alias": "televisionserviceproviders", "title": "Television Service Providers"],
                ["alias": "televisionstations", "title": "Television Stations"],
                ["alias": "tempura", "title": "Tempura"],
                ["alias": "tenantlaw", "title": "Tenant and Eviction Law"],
                ["alias": "tennis", "title": "Tennis"],
                ["alias": "teochew", "title": "Teochew"],
                ["alias": "teppanyaki", "title": "Teppanyaki"],
                ["alias": "testprep", "title": "Test Preparation"],
                ["alias": "tex-mex", "title": "Tex-Mex"],
                ["alias": "thai", "title": "Thai"],
                ["alias": "theater", "title": "Performing Arts"],
                ["alias": "themedcafes", "title": "Themed Cafes"],
                ["alias": "threadingservices", "title": "Threading Services"],
                ["alias": "thrift_stores", "title": "Thrift Stores"],
                ["alias": "tickets", "title": "Tickets"],
                ["alias": "ticketsales", "title": "Ticket Sales"],
                ["alias": "tikibars", "title": "Tiki Bars"],
                ["alias": "tiling", "title": "Tiling"],
                ["alias": "tires", "title": "Tires"],
                ["alias": "titleloans", "title": "Title Loans"],
                ["alias": "tobaccoshops", "title": "Tobacco Shops"],
                ["alias": "tofu", "title": "Tofu Shops"],
                ["alias": "tonkatsu", "title": "Tonkatsu"],
                ["alias": "torshi", "title": "Torshi"],
                ["alias": "tortillas", "title": "Tortillas"],
                ["alias": "tours", "title": "Tours"],
                ["alias": "towing", "title": "Towing"],
                ["alias": "towncarservice", "title": "Town Car Service"],
                ["alias": "townhall", "title": "Town Hall"],
                ["alias": "toxicologists", "title": "Toxicologists"],
                ["alias": "toys", "title": "Toy Stores"],
                ["alias": "tradamerican", "title": "American (Traditional)"],
                ["alias": "tradclothing", "title": "Traditional Clothing"],
                ["alias": "tradefairs", "title": "Trade Fairs"],
                ["alias": "traditional_swedish", "title": "Traditional Swedish"],
                ["alias": "trafficschools", "title": "Traffic Schools"],
                ["alias": "trafficticketinglaw", "title": "Traffic Ticketing Law"],
                ["alias": "trailerdealers", "title": "Trailer Dealers"],
                ["alias": "trailerrental", "title": "Trailer Rental"],
                ["alias": "trailerrepair", "title": "Trailer Repair"],
                ["alias": "trains", "title": "Trains"],
                ["alias": "trainstations", "title": "Train Stations"],
                ["alias": "trampoline", "title": "Trampoline Parks"],
                ["alias": "translationservices", "title": "Translation Services"],
                ["alias": "transmissionrepair", "title": "Transmission Repair"],
                ["alias": "transport", "title": "Transportation"],
                ["alias": "tras_os_montes", "title": "Tras-os-Montes"],
                ["alias": "trattorie", "title": "Trattorie"],
                ["alias": "travelagents", "title": "Travel Agents"],
                ["alias": "travelservices", "title": "Travel Services"],
                ["alias": "treeservices", "title": "Tree Services"],
                ["alias": "trinidadian", "title": "Trinidadian"],
                ["alias": "triviahosts", "title": "Trivia Hosts"],
                ["alias": "trophyshops", "title": "Trophy Shops"],
                ["alias": "truck_rental", "title": "Truck Rental"],
                ["alias": "truckdealers", "title": "Commercial Truck Dealers"],
                ["alias": "truckrepair", "title": "Commercial Truck Repair"],
                ["alias": "tubing", "title": "Tubing"],
                ["alias": "tuina", "title": "Tui Na"],
                ["alias": "turkish", "title": "Turkish"],
                ["alias": "turkishravioli", "title": "Turkish Ravioli"],
                ["alias": "tuscan", "title": "Tuscan"],
                ["alias": "tutoring", "title": "Tutoring Centers"],
                ["alias": "tvmounting", "title": "TV Mounting"],
                ["alias": "udon", "title": "Udon"],
                ["alias": "ukrainian", "title": "Ukrainian"],
                ["alias": "unagi", "title": "Unagi"],
                ["alias": "underseamedicine", "title": "Undersea/Hyperbaric Medicine"],
                ["alias": "uniforms", "title": "Uniforms"],
                ["alias": "university_housing", "title": "University Housing"],
                ["alias": "unofficialyelpevents", "title": "Unofficial Yelp Events"],
                ["alias": "urgent_care", "title": "Urgent Care"],
                ["alias": "urologists", "title": "Urologists"],
                ["alias": "usedbooks", "title": "Used Bookstore"],
                ["alias": "usedcardealers", "title": "Used Car Dealers"],
                ["alias": "utilities", "title": "Utilities"],
                ["alias": "uzbek", "title": "Uzbek"],
                ["alias": "vacation_rentals", "title": "Vacation Rentals"],
                ["alias": "vacationrentalagents", "title": "Vacation Rental Agents"],
                ["alias": "valetservices", "title": "Valet Services"],
                ["alias": "vapeshops", "title": "Vape Shops"],
                ["alias": "vascularmedicine", "title": "Vascular Medicine"],
                ["alias": "vegan", "title": "Vegan"],
                ["alias": "vegetarian", "title": "Vegetarian"],
                ["alias": "vehicleshipping", "title": "Vehicle Shipping"],
                ["alias": "vehiclewraps", "title": "Vehicle Wraps"],
                ["alias": "venetian", "title": "Venetian"],
                ["alias": "venezuelan", "title": "Venezuelan"],
                ["alias": "venison", "title": "Venison"],
                ["alias": "venues", "title": "Venues & Event Spaces"],
                ["alias": "vermouthbars", "title": "Vermouth Bars"],
                ["alias": "vet", "title": "Veterinarians"],
                ["alias": "veteransorganizations", "title": "Veterans Organizations"],
                ["alias": "videoandgames", "title": "Videos & Video Game Rental"],
                ["alias": "videofilmproductions", "title": "Video/Film Production"],
                ["alias": "videogamestores", "title": "Video Game Stores"],
                ["alias": "videographers", "title": "Videographers"],
                ["alias": "vietnamese", "title": "Vietnamese"],
                ["alias": "vintage", "title": "Used, Vintage & Consignment"],
                ["alias": "vinyl_records", "title": "Vinyl Records"],
                ["alias": "vinylsiding", "title": "Vinyl Siding"],
                ["alias": "visitorcenters", "title": "Visitor Centers"],
                ["alias": "vitaminssupplements", "title": "Vitamins & Supplements"],
                ["alias": "vocation", "title": "Vocational & Technical School"],
                ["alias": "volleyball", "title": "Volleyball"],
                ["alias": "waffles", "title": "Waffles"],
                ["alias": "waldorfschools", "title": "Waldorf Schools"],
                ["alias": "walkinclinics", "title": "Walk-in Clinics"],
                ["alias": "walkingtours", "title": "Walking Tours"],
                ["alias": "watch_repair", "title": "Watch Repair"],
                ["alias": "watches", "title": "Watches"],
                ["alias": "waterdelivery", "title": "Water Delivery"],
                ["alias": "waterheaterinstallrepair", "title": "Water Heater Installation/Repair"],
                ["alias": "waterparks", "title": "Water Parks"],
                ["alias": "waterproofing", "title": "Waterproofing"],
                ["alias": "waterpurification", "title": "Water Purification Services"],
                ["alias": "waterstores", "title": "Water Stores"],
                ["alias": "watertaxis", "title": "Water Taxis"],
                ["alias": "waxing", "title": "Waxing"],
                ["alias": "web_design", "title": "Web Design"],
                ["alias": "wedding_planning", "title": "Wedding Planning"],
                ["alias": "weddingchappels", "title": "Wedding Chapels"],
                ["alias": "weightlosscenters", "title": "Weight Loss Centers"],
                ["alias": "welldrilling", "title": "Well Drilling"],
                ["alias": "westernjapanese", "title": "Western Style Japanese Food"],
                ["alias": "whalewatchingtours", "title": "Whale Watching Tours"],
                ["alias": "wheelrimrepair", "title": "Wheel & Rim Repair"],
                ["alias": "whiskeybars", "title": "Whiskey Bars"],
                ["alias": "wholesale_stores", "title": "Wholesale Stores"],
                ["alias": "wholesalers", "title": "Wholesalers"],
                ["alias": "wigs", "title": "Wigs"],
                ["alias": "wildlifecontrol", "title": "Wildlife Control"],
                ["alias": "wildlifehunting", "title": "Wildlife Hunting Ranges"],
                ["alias": "willstrustsprobates", "title": "Wills, Trusts, & Probates"],
                ["alias": "windowsinstallation", "title": "Windows Installation"],
                ["alias": "windowwashing", "title": "Window Washing"],
                ["alias": "windshieldinstallrepair", "title": "Windshield Installation & Repair"],
                ["alias": "wine_bars", "title": "Wine Bars"],
                ["alias": "wineries", "title": "Wineries"],
                ["alias": "winetasteclasses", "title": "Wine Tasting Classes"],
                ["alias": "winetastingroom", "title": "Wine Tasting Room"],
                ["alias": "winetours", "title": "Wine Tours"],
                ["alias": "wok", "title": "Wok"],
                ["alias": "womenscloth", "title": "Women's Clothing"],
                ["alias": "workerscomplaw", "title": "Workers Compensation Law"],
                ["alias": "wraps", "title": "Wraps"],
                ["alias": "xmasmarkets", "title": "Christmas Markets"],
                ["alias": "yakiniku", "title": "Yakiniku"],
                ["alias": "yakitori", "title": "Yakitori"],
                ["alias": "yelpevents", "title": "Yelp Events"],
                ["alias": "yoga", "title": "Yoga"],
                ["alias": "youth_club", "title": "Youth Club"],
                ["alias": "yucatan", "title": "Yucatan"],
                ["alias": "yugoslav", "title": "Yugoslav"],
                ["alias": "zapiekanka", "title": "Zapiekanka"],
                ["alias": "zipline", "title": "Ziplining"],
                ["alias": "zoos", "title": "Zoos"],
                ["alias": "zorbing", "title": "Zorbing"]]
    }
}
