//
//  Category.swift
//  Yelp
//
//  Created by Josh Jeong on 4/7/17.
//  Copyright © 2017 Timothy Lee. All rights reserved.
//

import Foundation

class Category {
    
    func getFoodCategories() -> [[String:String]] {
        return [["title" : "Afghan", "alias": "afghani"],
                ["title" : "African", "alias": "african"],
                ["title" : "American, New", "alias": "newamerican"],
                ["title" : "American, Traditional", "alias": "tradamerican"],
                ["title" : "Arabian", "alias": "arabian"],
                ["title" : "Argentine", "alias": "argentine"],
                ["title" : "Armenian", "alias": "armenian"],
                ["title" : "Asian Fusion", "alias": "asianfusion"],
                ["title" : "Asturian", "alias": "asturian"],
                ["title" : "Australian", "alias": "australian"],
                ["title" : "Austrian", "alias": "austrian"],
                ["title" : "Baguettes", "alias": "baguettes"],
                ["title" : "Bangladeshi", "alias": "bangladeshi"],
                ["title" : "Barbeque", "alias": "bbq"],
                ["title" : "Basque", "alias": "basque"],
                ["title" : "Bavarian", "alias": "bavarian"],
                ["title" : "Beer Garden", "alias": "beergarden"],
                ["title" : "Beer Hall", "alias": "beerhall"],
                ["title" : "Beisl", "alias": "beisl"],
                ["title" : "Belgian", "alias": "belgian"],
                ["title" : "Bistros", "alias": "bistros"],
                ["title" : "Black Sea", "alias": "blacksea"],
                ["title" : "Brasseries", "alias": "brasseries"],
                ["title" : "Brazilian", "alias": "brazilian"],
                ["title" : "Breakfast & Brunch", "alias": "breakfast_brunch"],
                ["title" : "British", "alias": "british"],
                ["title" : "Buffets", "alias": "buffets"],
                ["title" : "Bulgarian", "alias": "bulgarian"],
                ["title" : "Burgers", "alias": "burgers"],
                ["title" : "Burmese", "alias": "burmese"],
                ["title" : "Cafes", "alias": "cafes"],
                ["title" : "Cafeteria", "alias": "cafeteria"],
                ["title" : "Cajun/Creole", "alias": "cajun"],
                ["title" : "Cambodian", "alias": "cambodian"],
                ["title" : "Canadian", "alias": "New)"],
                ["title" : "Canteen", "alias": "canteen"],
                ["title" : "Caribbean", "alias": "caribbean"],
                ["title" : "Catalan", "alias": "catalan"],
                ["title" : "Chech", "alias": "chech"],
                ["title" : "Cheesesteaks", "alias": "cheesesteaks"],
                ["title" : "Chicken Shop", "alias": "chickenshop"],
                ["title" : "Chicken Wings", "alias": "chicken_wings"],
                ["title" : "Chilean", "alias": "chilean"],
                ["title" : "Chinese", "alias": "chinese"],
                ["title" : "Comfort Food", "alias": "comfortfood"],
                ["title" : "Corsican", "alias": "corsican"],
                ["title" : "Creperies", "alias": "creperies"],
                ["title" : "Cuban", "alias": "cuban"],
                ["title" : "Curry Sausage", "alias": "currysausage"],
                ["title" : "Cypriot", "alias": "cypriot"],
                ["title" : "Czech", "alias": "czech"],
                ["title" : "Czech/Slovakian", "alias": "czechslovakian"],
                ["title" : "Danish", "alias": "danish"],
                ["title" : "Delis", "alias": "delis"],
                ["title" : "Diners", "alias": "diners"],
                ["title" : "Dumplings", "alias": "dumplings"],
                ["title" : "Eastern European", "alias": "eastern_european"],
                ["title" : "Ethiopian", "alias": "ethiopian"],
                ["title" : "Fast Food", "alias": "hotdogs"],
                ["title" : "Filipino", "alias": "filipino"],
                ["title" : "Fish & Chips", "alias": "fishnchips"],
                ["title" : "Fondue", "alias": "fondue"],
                ["title" : "Food Court", "alias": "food_court"],
                ["title" : "Food Stands", "alias": "foodstands"],
                ["title" : "French", "alias": "french"],
                ["title" : "French Southwest", "alias": "sud_ouest"],
                ["title" : "Galician", "alias": "galician"],
                ["title" : "Gastropubs", "alias": "gastropubs"],
                ["title" : "Georgian", "alias": "georgian"],
                ["title" : "German", "alias": "german"],
                ["title" : "Giblets", "alias": "giblets"],
                ["title" : "Gluten-Free", "alias": "gluten_free"],
                ["title" : "Greek", "alias": "greek"],
                ["title" : "Halal", "alias": "halal"],
                ["title" : "Hawaiian", "alias": "hawaiian"],
                ["title" : "Heuriger", "alias": "heuriger"],
                ["title" : "Himalayan/Nepalese", "alias": "himalayan"],
                ["title" : "Hong Kong Style Cafe", "alias": "hkcafe"],
                ["title" : "Hot Dogs", "alias": "hotdog"],
                ["title" : "Hot Pot", "alias": "hotpot"],
                ["title" : "Hungarian", "alias": "hungarian"],
                ["title" : "Iberian", "alias": "iberian"],
                ["title" : "Indian", "alias": "indpak"],
                ["title" : "Indonesian", "alias": "indonesian"],
                ["title" : "International", "alias": "international"],
                ["title" : "Irish", "alias": "irish"],
                ["title" : "Island Pub", "alias": "island_pub"],
                ["title" : "Israeli", "alias": "israeli"],
                ["title" : "Italian", "alias": "italian"],
                ["title" : "Japanese", "alias": "japanese"],
                ["title" : "Jewish", "alias": "jewish"],
                ["title" : "Kebab", "alias": "kebab"],
                ["title" : "Korean", "alias": "korean"],
                ["title" : "Kosher", "alias": "kosher"],
                ["title" : "Kurdish", "alias": "kurdish"],
                ["title" : "Laos", "alias": "laos"],
                ["title" : "Laotian", "alias": "laotian"],
                ["title" : "Latin American", "alias": "latin"],
                ["title" : "Live/Raw Food", "alias": "raw_food"],
                ["title" : "Lyonnais", "alias": "lyonnais"],
                ["title" : "Malaysian", "alias": "malaysian"],
                ["title" : "Meatballs", "alias": "meatballs"],
                ["title" : "Mediterranean", "alias": "mediterranean"],
                ["title" : "Mexican", "alias": "mexican"],
                ["title" : "Middle Eastern", "alias": "mideastern"],
                ["title" : "Milk Bars", "alias": "milkbars"],
                ["title" : "Modern Australian", "alias": "modern_australian"],
                ["title" : "Modern European", "alias": "modern_european"],
                ["title" : "Mongolian", "alias": "mongolian"],
                ["title" : "Moroccan", "alias": "moroccan"],
                ["title" : "New Zealand", "alias": "newzealand"],
                ["title" : "Night Food", "alias": "nightfood"],
                ["title" : "Norcinerie", "alias": "norcinerie"],
                ["title" : "Open Sandwiches", "alias": "opensandwiches"],
                ["title" : "Oriental", "alias": "oriental"],
                ["title" : "Pakistani", "alias": "pakistani"],
                ["title" : "Parent Cafes", "alias": "eltern_cafes"],
                ["title" : "Parma", "alias": "parma"],
                ["title" : "Persian/Iranian", "alias": "persian"],
                ["title" : "Peruvian", "alias": "peruvian"],
                ["title" : "Pita", "alias": "pita"],
                ["title" : "Pizza", "alias": "pizza"],
                ["title" : "Polish", "alias": "polish"],
                ["title" : "Portuguese", "alias": "portuguese"],
                ["title" : "Potatoes", "alias": "potatoes"],
                ["title" : "Poutineries", "alias": "poutineries"],
                ["title" : "Pub Food", "alias": "pubfood"],
                ["title" : "Rice", "alias": "riceshop"],
                ["title" : "Romanian", "alias": "romanian"],
                ["title" : "Rotisserie Chicken", "alias": "rotisserie_chicken"],
                ["title" : "Rumanian", "alias": "rumanian"],
                ["title" : "Russian", "alias": "russian"],
                ["title" : "Salad", "alias": "salad"],
                ["title" : "Sandwiches", "alias": "sandwiches"],
                ["title" : "Scandinavian", "alias": "scandinavian"],
                ["title" : "Scottish", "alias": "scottish"],
                ["title" : "Seafood", "alias": "seafood"],
                ["title" : "Serbo Croatian", "alias": "serbocroatian"],
                ["title" : "Signature Cuisine", "alias": "signature_cuisine"],
                ["title" : "Singaporean", "alias": "singaporean"],
                ["title" : "Slovakian", "alias": "slovakian"],
                ["title" : "Soul Food", "alias": "soulfood"],
                ["title" : "Soup", "alias": "soup"],
                ["title" : "Southern", "alias": "southern"],
                ["title" : "Spanish", "alias": "spanish"],
                ["title" : "Steakhouses", "alias": "steak"],
                ["title" : "Sushi Bars", "alias": "sushi"],
                ["title" : "Swabian", "alias": "swabian"],
                ["title" : "Swedish", "alias": "swedish"],
                ["title" : "Swiss Food", "alias": "swissfood"],
                ["title" : "Tabernas", "alias": "tabernas"],
                ["title" : "Taiwanese", "alias": "taiwanese"],
                ["title" : "Tapas Bars", "alias": "tapas"],
                ["title" : "Tapas/Small Plates", "alias": "tapasmallplates"],
                ["title" : "Tex-Mex", "alias": "tex-mex"],
                ["title" : "Thai", "alias": "thai"],
                ["title" : "Traditional Norwegian", "alias": "norwegian"],
                ["title" : "Traditional Swedish", "alias": "traditional_swedish"],
                ["title" : "Trattorie", "alias": "trattorie"],
                ["title" : "Turkish", "alias": "turkish"],
                ["title" : "Ukrainian", "alias": "ukrainian"],
                ["title" : "Uzbek", "alias": "uzbek"],
                ["title" : "Vegan", "alias": "vegan"],
                ["title" : "Vegetarian", "alias": "vegetarian"],
                ["title" : "Venison", "alias": "venison"],
                ["title" : "titlese", "alias": "titlese"],
                ["title" : "Wok", "alias": "wok"],
                ["title" : "Wraps", "alias": "wraps"],
                ["title" : "Yugoslav", "alias": "yugoslav"]]
    }
}
